### ISSUE TITLE
Question: Connection unstable with direct link

### ISSUE THREAD

**Issue by hzhwcmhf** [zerotier/ZeroTierOne#1049]
I have 2 nodes in a network. Both updated to the newest version and I have checked none of them are in fallback mode. (Using ``zerotier-cli info -j``)

A: Windows 10, behind a Port-Restricted Cone NAT, with UPnP enabled.
B: An AWS EC instance, allowing all UDP ingoing and outgoing.

I check the status with  ``zerotier-cli peers``, both nodes think they have a direct connection.
The connection seems normal sometimes, but it won't last too long (about 1 or 2 minutes).
At most of the time, I can't ping each other or establish tcp connections using 192.168.XX.XX. I have shutdown the firewalls.

I have another node C, which have a public ip. It can connect normally with both A and B (including ping or other tcp connections).

Do you have any ideas about the problem? Thanks!

**Comment by DominicWrege** [comment]
I have almost the same issue as you.

**Comment by unquietwiki** [comment]
@hzhwcmhf @DominicWrege 

I'm going over our GitHub issues in preparation for our pending 1.6.0 release; that should hopefully take care of a few things. If you're still having this issue ATM, can you please check the following & let us know otherwise so we can try to catch it? Thanks!

* https://zerotier.atlassian.net/wiki/spaces/SD/pages/521011201/Windows+Troubleshooting -> Walkthrough of common Windows issues.
* https://zerotier.atlassian.net/wiki/spaces/SD/pages/7503890/ZeroTier+to+Amazon+VPC+Gateway -> AWS issues with ZT
* https://discuss.zerotier.com/ -> Official Discuss forum

**Comment by hzhwcmhf** [comment]
Thanks for your reply, but I don't use AWS now and cannot reproduce the problem.

**Comment by unquietwiki** [comment]
Thank you @hzhwcmhf
