### ISSUE TITLE
NDIS 6 Windows tap driver

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#107]
User reported failure to start driver with "code 30" on this Windows version:

![255i9aw](https://cloud.githubusercontent.com/assets/591635/4018811/ab64293e-2a55-11e4-9e59-5549d565faac.jpg)

**Comment by cyph84** [comment]
Recently I dealt with a completely unpatched Windows 7 install which I was hesitant to apply sweeping updates (for various reasons mostly due to the fragility of the stuff thats running on it).

It seems that this: https://support.microsoft.com/en-us/kb/2685811 patch which upgrades KMDF from 1.9 to 1.11 is one of the "millions of patches" that allows the driver to be loaded and initialized.
