### ISSUE TITLE
Node ID Unknown after reboot Windows 10 build 2004

### ISSUE THREAD

**Issue by kordeiro** [zerotier/ZeroTierOne#1210]
**Describe the bug**
Node ID is unknown when ZeroTier starts automatically after reboot.

**To Reproduce**
1. Reboot Windows
2. Let ZeroTier start automatically
3. Node ID is unknown

**Expected behavior**
The Node ID should be visible. Restarting ZeroTier fixes the issue.

**Screenshots**
If applicable, add screenshots or console output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - OS/Distribution Version: 10 2004
 - ZeroTier Version 1.4.6
 - Hardware Desktop

**Comment by kordeiro** [comment]
Seems related to issue [1208](https://github.com/zerotier/ZeroTierOne/issues/1208)

**Comment by unquietwiki** [comment]
@kordeiro @BaldStrong I'm going over our GitHub issues in preparation for our pending 1.6.0 release; that should hopefully take care of a few things. If you're still having this issue ATM, can you please check the following & let us know otherwise so we can try to catch it? Thanks!

* https://zerotier.atlassian.net/wiki/spaces/SD/pages/521011201/Windows+Troubleshooting -> Walkthrough of common Windows issues.
* https://www.reddit.com/r/zerotier/?f=flair_name%3A%22Gaming%22 -> A lot of gamers & Windows users have figured out some stuff.
* https://discuss.zerotier.com/ -> Official Discuss forum

**Comment by rexxfan** [comment]
Thanks for that.  As it turns out, I was able to solve this problem a couple of months ago by following the directions for **FIX 1** as described here [https://thegeekpage.com/fix-ipv6-connectivity-no-network-access-error-in-windows-10/](url). I should have posted that information back here. Please forgive me for forgetting to do that.

**Comment by unquietwiki** [comment]
@rexxfan Thanks for that. I'll add that to our notes!!!
