### ISSUE TITLE
windows 10 1909 zttap300 driver, status: port_error

### ISSUE THREAD

**Issue by Dimon-Easy** [zerotier/ZeroTierOne#1217]
**Describe the bug**
On fresh windows 10 1909 build 18363.90 after install ZeroTier One.msi v1.4.6, ZeroTier One Virtual Port driver didn't install completely

**To Reproduce**
1. install windows x64 10 1909 build 18363.90
2. Install zerotier-one '1.4.6'
3. try join some zt network, you get status: port_error in zt GUI 
4. check windows device manager, you get network card unknown device

**Expected behavior**
ZeroTier One Virtual Port driver install properly

**Desktop (please complete the following information):**
 - OS: windows 10 x64 1909 (build 18363.90)
 - OS/Distribution Version
 - ZeroTier Version 1.4.6
 - Asus k56cb laptop

**Screenshots**
![1](https://user-images.githubusercontent.com/10555466/84755348-3ffcad00-afca-11ea-89fc-a0741a8bd062.jpg)
![2](https://user-images.githubusercontent.com/10555466/84755342-3e32e980-afca-11ea-818a-f59f765d1a0a.jpg)
![3](https://user-images.githubusercontent.com/10555466/84755345-3f641680-afca-11ea-9f86-0aa9b4c351dc.jpg)
![manual install](https://user-images.githubusercontent.com/10555466/84755347-3f641680-afca-11ea-95de-02f8bf920003.jpg)

**Comment by KittyBabyMan** [comment]
Hi. My friend is having the same issue here with my friend. He's stuck on 'PORT_ERROR' as well. It seems like his driver for zerotier does not want to install at all.

Attached is his port error log.
a84ac5c10affb048: unable to create new device instance: UpdateDriverForPlugAndPlayDevices() failed (made 60 attempts)

[port_error_log.txt](https://github.com/zerotier/ZeroTierOne/files/4842669/port_error_log.txt)

**Comment by festro** [comment]
same issue here I've tried uninstalling ZT, resetting windows network, and reinstalling. The GUI shows to be connected after a "Cannot connect to ZeroTier service" error message, get a port_error in the GUI and driver shows up in device manager as an "Unknown device" and is not present in the network connections in any capacity.

**Comment by unquietwiki** [comment]
@Dimon-Easy @KittyBabyMan @festro I'm going over our GitHub issues in preparation for our pending 1.6.0 release; that should hopefully take care of a few things. If you're still having this issue ATM, can you please check the following & let us know otherwise so we can try to catch it? Thanks!

* https://zerotier.atlassian.net/wiki/spaces/SD/pages/521011201/Windows+Troubleshooting -> Walkthrough of common Windows issues.
* https://www.reddit.com/r/zerotier/?f=flair_name%3A%22Gaming%22 -> A lot of gamers & Windows users have figured out some stuff.
* https://discuss.zerotier.com/ -> Official Discuss forum

**Comment by Dimon-Easy** [comment]
issue is still present

**Comment by unquietwiki** [comment]
@Dimon-Easy I found your issue in our Jira and linked it to here. If you didn't already try it, please look at https://lifehacker.com/blame-this-windows-10-bug-for-your-recent-vpn-issues-1842587669 ; there is a known issue with VPN clients for some Windows 10 users; https://support.microsoft.com/en-us/help/4554364/windows-10-update-kb4554364 is the actual patch.

Also, since we use a modified version of the OpenVPN driver, please make sure you're not already using OpenVPN. If you really want to get into the weeds, https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/uninstall-tap-windows-adapter-v9/569f4e8b-447f-4bce-8f4d-6f60a1da26a4?auth=1 will be helpful here; uninstall ZeroTier, use **tapinstall remove zttap300** on step 5, and reinstall ZeroTier when done.

If that doesn't work, your next best thing might be to wait until we have 1.6.0 ready, which is being finalized at the moment.

Thank you for your patience.

**Comment by Dimon-Easy** [comment]
issue resolved for me when i remove TAP-Windows Adapter V9 inf file from windows driver store 😊

**Comment by unquietwiki** [comment]
@Dimon-Easy good to hear!!!
