### ISSUE TITLE
ZeroTier One empty window although connected

### ISSUE THREAD

**Issue by user398** [zerotier/ZeroTierOne#1231]
On Windows the ZeroTier One system tray icon shows an empty window when I click on "Show Networks". It also shows "Node ID: Unknown" although I'm connected and all is good (can ping, can see my machine online in Members).

I have version 1.4.6 with custom UDP port set in local.conf that is port-forwarded on the ISP router. I also port forwarded the default port 9993 for troubleshooting but I get the same behavior.

Restarted computer and the problem remains.

`zerotier-cli -j info` shows custom port in use, and `"online": true`

Edit: ZeroTier One is whitelisted in wf.msc for all ports out and in and for all type networks but cannot reach the servers when using a custom port other than 9993.

**Comment by unquietwiki** [comment]
@user398 I'm going over our GitHub issues in preparation for our pending 1.6.0 release; that should hopefully take care of a few things. If you're still having this issue ATM, can you please check the following & let us know otherwise so we can try to catch it? Thanks!

* https://zerotier.atlassian.net/wiki/spaces/SD/pages/521011201/Windows+Troubleshooting -> Walkthrough of common Windows issues.
* https://www.reddit.com/r/zerotier/?f=flair_name%3A%22Gaming%22 -> A lot of gamers & Windows users have figured out some stuff.
* https://discuss.zerotier.com/ -> Official Discuss forum
