### ISSUE TITLE
Entware device can't be accessed

### ISSUE THREAD

**Issue by glblduh** [zerotier/ZeroTierOne#1342]
The ZeroTier Centrals shows that it is online and authorized but the entware don't have the routes that I set in the Central and the device can't be pinged and can't ping other peers. My Entware version is armv7sf-k3.2 and I installed the zerotier package using opkg 

This is the output of the route command
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.0.1     0.0.0.0         UG    202    0        0 eth0
10.13.37.0      *               255.255.255.0   U     0      0        0 ztnfaldw2j
192.168.0.0     *               255.255.255.0   U     0      0        0 eth0
192.168.0.0     *               255.255.255.0   U     202    0        0 eth0

**Comment by adamierymenko** [comment]
This may be a #1334 duplicate

**Comment by joseph-henry** [comment]
@glblduh Which version of ZeroTier were you using? And are you still seeing this issue?

**Comment by glblduh** [comment]
The ZeroTier I'm using is the latest on the Entware (armv7sf-k3.2) repo which is version 1.4.6-5.

**Comment by joseph-henry** [comment]
Closing due to age. But two things to consider:

 - I've personally noticed `10.*` subnets to be problematic and unpredictable and so I avoid them. I think it's some conflict with my default route and my ISP's infrastructure but I don't know how exactly. I've noticed this with two different ISPs, simply changing the subnet to something like `192.168.192.*` would fix these mysterious `10.*` issues.
 
 - Depending on the device you're installing this on, make sure there isn't some daemon removing your routes. We noticed Synology does this and it was puzzling for a while.
 
 If this is still an issue for you please request that we reopen this and I can take a closer look. Good luck!
