### ISSUE TITLE
make it easier to use own supernode

### ISSUE THREAD

**Issue by maci0** [zerotier/ZeroTierOne#139]
Hi, I think it should be made easier to use your own supernode.
With n2n it was quite easy, just run it somewhere and point your client to the supernode.
It would be great of ZTO would offer the same functionality...Maybe an option in the web-interface to specify a node as supernode and also an option to not use the public supernodes would be cool.

**Comment by adamierymenko** [comment]
This is a complex issue.

The architecture and goal of ZeroTier One is a bit different from N2N. The idea of ZT1 is to do software defined networking at global scale. You should be able to create a virtual network and then add *anything* to it, no matter where that thing is, and you should not have to worry much about anything else. It should be as near to "zero configuration" as possible.

The fixed global supernodes model is designed to facilitate that. I have a post here where I discuss the design trade-offs in some depth:

http://adamierymenko.com/decentralization-i-want-to-believe/

I do plan to introduce some concept of federating in the future. This will likely be an enterprise feature for people who want to run in-house supernodes at, say, a data center. But as it stands I'm not planning to make ZT1 the same as N2N because its goals are different.
