### ISSUE TITLE
How to orbit moon on ios devices? 

### ISSUE THREAD

**Issue by Mx1014** [zerotier/ZeroTierOne#1429]
How to orbit moon on  ios devices? Or maybe allow we can provide moon server as root?

**Comment by laduke** [comment]
There is no option for moons on mobile. Maybe someday in the far future or something that accomplishes the same thing.

**Comment by matglas** [comment]
Maybe it would be an idea to allow moons to be defined by the config on the Zerotier panel.

**Comment by laduke** [comment]
Thanks for the requests and suggestions. We are tracking this feature. Closing because it's not actionable for zerotier-one. But please feel free to continue chatting here. 

there are some related threads https://github.com/zerotier/ZeroTierOne/issues?q=is%3Aissue+moon+is%3Aclosed

**Comment by chengyuhui** [comment]
Developers have successfully added this feature to the Android client: https://github.com/kaaass/ZerotierFix, meaning that this is certainly actionable. Modding the iOS client is currently not possible, otherwise I'm sure people will try to do that.

Unable to orbit to moons is a deal breaker in China, where in some regions and ISPs the official servers are barely accessible.
