### ISSUE TITLE
Path learning and selection issues

### ISSUE THREAD

**Issue by allenforrest** [zerotier/ZeroTierOne#1521]
Dear all:

In the V1 codebase, the `Peer::received` contains the path learning mechanism and `Peer::getAppropriatePath` will choose the best path among all learned direct paths.

The confusing scenario is:

- A ZT node in the Wi-Fi network contacted the roots, all the Wi-Fi paths have been learned and saved in the `_paths` list in the root node (e.g. 1.2.3.4:9993 and other two ports).
- Then the ZT node changes the network to a worse Cellular one, it re-contacts the root node via the new Cellular endpoint address (e.g. 10.10.10.10:9993 and other two ports). Now the old Wi-Fi paths are alive and the new Cellular paths will be saved in the blank slots of `_paths` list.
- After that, when choosing the best path in `getAppropriatePath`, all the paths are alive and the old Wi-Fi paths (1.2.3.4:9993) may have the better quality (lower latency) and will be elected inappropriately (actually they are dead).
- Till the old Wi-Fi paths (1.2.3.4:9993) aged (after ZT_PATH_HEARTBEAT_PERIOD + 5000 = 19s), they will be replaced with the Cellular paths or the quality will be re-calculated into a very larger value, the path selection will be correct.

I know that it is an unusual scenario and can be recovered within several seconds, but in that fake alive status, both ZT nodes cannot communicate with each other, the user must be patient and wait for a while.

So are there some ideas about this issue improvement? Maybe add a punishment score over the fake alive paths?

Thanks so much.

**Comment by joseph-henry** [comment]
This is a known behavior that doesn't have an ideal solution. On one hand ZT is "efficient" in terms of overhead by not polling the links too often, but this has the side-effect of not knowing quickly if a link has truly failed. On the other hand we could poll the links more often, know more quickly and be able to switch fast but that would create a lot of overhead. We are hesitant to introduce one more "knob" for people to tweak since that can make debugging harder.

The only thing that I can suggest that might work for you is using the `active-backup` multipath mode described [here](https://docs.zerotier.com/zerotier/multipath#active-backup-active-backup). With this you can set a failover interval (say 2s) and it will poll the links every `failover / 4`, so `500ms`. This creates more overhead but it will switch as quickly as you need it to.

Let me know if you have any questions on that.

**Comment by allenforrest** [comment]
Thanks for your reply and explanation.

The `active-backup` multipath mechanism your proposed may not be suitable for this scenario. IMO the multipath is based on the independent physical interface. From the root node point of view, whatever the client node uses the Wi-Fi or Cellular link, the only one physical interface(e.g. eth0 in Linux OS of AWS VM) is used in the root node, so I cannot configure the multipath in the root nodes. Is it right? If I made some misunderstandings of the multipath feature, please let me know. 

I have read the V2 branch(v2-before-rusting) codes(not yet updated in a while) and found there is a new implementation of path learning and priority election:

- Introduce a `m_prioritizePaths` for path re-sorting and prioritized selection.
- When a new path is discovered, add it to the candidate path list, re-sorting and updating the `m_prioritizePaths`.
- Use the path `lastIn` instead of the `quality` to sort paths. So the new learned path is more prior to the fake alive one, even if the quality of the new path is worse than the old one.

It seems to be able to solve the issue I submit, but maybe the `lastIn` sorting is not as fair as the RTT based sorting `quality`?

**Comment by joseph-henry** [comment]
There have been changes in the `dev` branch which should help here. They'll make it into `1.8.6` but they're ready to try today. Essentially the improvements do the following:

- Proactively gather *all* interface addresses instead of waiting until the one in use dies (no multipath needed)

Without using multipath the above will only be a marginal improvement. After also enabling `active-backup` and setting the failover to your desired time you'll see very rapid interface changes.

>  IMO the multipath is based on the independent physical interface. From the root node point of view, whatever the client node uses the Wi-Fi or Cellular link, the only one physical interface(e.g. eth0 in Linux OS of AWS VM) is used in the root node, so I cannot configure the multipath in the root nodes. Is it right? If I made some misunderstandings of the multipath feature, please let me know.

I'm not certain why the multipath to the non-leaf node would matter in this case but when multipath is enabled they do now establish `active-backup` bonds to all non-leaf nodes automatically.

Please let me know if there's anything I can clarify further.
