### ISSUE TITLE
Waiting for ZeroTier system service... clean install on windows 10 21H1 1.8.5 zerotier

### ISSUE THREAD

**Issue by JuanjoNuevo** [zerotier/ZeroTierOne#1576]
- What you expect to be happening:
ZeroTierOne working and showing the UI insteed waiting for service that's already on.

- What is actually happening?
I've just installed the program, and it says waiting for zerotier system service. If i go to task manager, the service is already running but cannot access UI cause says waiting for zerotier system service.

- Any steps to reproduce the error.
Just install the msi latest version on windows

- Any relevant console output or screenshots
![WhatsApp Image 2022-03-04 at 1 01 17 PM](https://user-images.githubusercontent.com/58025382/156759984-e85f8748-37f4-4063-9279-4af882f7418f.jpeg)

- What operating system and ZeroTier version. Please try the latest ZeroTier release. 
Windows 10 Home 21H1   1.8.5 ZeroTier realease msi.

**Comment by JuanjoNuevo** [comment]
![WhatsApp Image 2022-03-04 at 1 03 55 PM](https://user-images.githubusercontent.com/58025382/156760293-5c26cc83-0401-4437-8fcb-44e20bf20a8d.jpeg)
More screenshots, service is running, i tried rebooting the pc, stoping and start again the service, reinstalling the app.... nothing.

**Comment by knw257** [comment]
I had the same problem - a friend of mine who runs their client on Linux figured out a solution that also seems to work on Windows. What you need to do is have the service join a network. You can open a command prompt at C:\ProgramData\ZeroTier\One, and run the command zerotier-one_x64.exe -q join <network ID>. This tells the service to join the network, after which the UI should be able to connect.

The issue appears to be that the UI client is trying to connect to the service via 127.0.0.1:9993, but receives no response, despite the service running. There may be a bug in the latest version that prevents UI connections until after a network is joined, but since the installer doesn't ask for a network ID, any new installations will likely need to join via CLI before the GUI will work properly.

I hope this helps, and hopefully a Dev will find this post and fix the apparent bug (or else write a KB article if there's a different way to fix this)

**Comment by JuanjoNuevo** [comment]
> I had the same problem - a friend of mine who runs their client on Linux figured out a solution that also seems to work on Windows. What you need to do is have the service join a network. You can open a command prompt at C:\ProgramData\ZeroTier\One, and run the command zerotier-one_x64.exe -q join . This tells the service to join the network, after which the UI should be able to connect.
> 
> The issue appears to be that the UI client is trying to connect to the service via 127.0.0.1:9993, but receives no response, despite the service running. There may be a bug in the latest version that prevents UI connections until after a network is joined, but since the installer doesn't ask for a network ID, any new installations will likely need to join via CLI before the GUI will work properly.
> 
> I hope this helps, and hopefully a Dev will find this post and fix the apparent bug (or else write a KB article if there's a different way to fix this)

@knw257 I managed to connect the peers to the net, ty. after all the UI client still on same position, don't wanna show and still says Waiting for ZeroTier system service.... but at least it runs. 

![image](https://user-images.githubusercontent.com/58025382/156927605-8525f29b-343b-44a6-8dd5-e2c200232e3b.png)

**Comment by glimberg** [comment]
There was a bug in 1.8.5 where an empty network list was sent back to the UI client as an error causing the 'Waiting for ZeroTier system service...'.  Joining a network from the command line would fix it since the network list was no longer empty.  This was resolved in 1.8.6

**Comment by ItsaPerryBob** [comment]
Its bugged over here but I joined a network via cmd and using zerotier-cli :)
