### ISSUE TITLE
instability on Linux machines

### ISSUE THREAD

**Issue by PatrykW-95** [zerotier/ZeroTierOne#1590]
Hi, after many tests on different platforms, kernels, networks etc I'm stuck with always the same weird issue i'm going to explain:
LAN 1 office:
**A)** Windows 11 (Zerotier-one 1.8.6)
**B)** Debian 11 (Zerotier-one 1.8.6 (builded with debug option))(VM On W11 with bridged ethernet adapter) 

LAN 2 home:
**C)** Windows 11 (Zerotier-one 1.8.6)
**D)** Debian 11 (Zerotier-one 1.8.6 (builded with debug option))(VM On W11 with bridged ethernet adapter) 

LAN 1 and 2 are two separated networks kilometers apart.

All machine have NetCat (on window 11 I'm using NCat from [nmap](https://nmap.org/) as suggested [here](https://superuser.com/questions/14501/are-there-netcat-like-tools-for-windows-which-are-not-quarantined-as-malware) ).

If on **A** I start NC listening and use **C**  to connect to it (or viceversa) works all perfectly with relativly low latency.
if on **B** I start NC listener  and use **C** or **D** only sometime I'm able to send a packet and recive it.
The same behavior occurs when the listeners are in "LAN 2 home" and  use  ZTs from office as clients.

It seems that Windows clients works well bidirectionally whilst the Linux client has problem receiving packets

On debian i've build it from the [master branch](https://github.com/zerotier/ZeroTierOne/commit/4a2c75a60941e75f36ed1961458a42fbd12ea4ac) and make it run form command line.
In the output i've found that the debians are continuously requesting configuration for network(about every 10 secs) and in the moment i try to connect with nc cames out `MAC failed for packet 97127342bb532374 from 38b02ee846(xxx.xxx.xxx.xxx/9993)`.
I'm using controller on my.zerotier.com where all zerotiers are authorized and online.
I've alse tried older versions like 1.4.4. ,1.4.6., 1.8.4., 1.8.5.

**Comment by PatrykW-95** [comment]
I've tried it and it seems to be working but using netcat every 10 packet i send only 3 arrives correctly.
I'd like to specify that in every version i tested the behaviour is the same and i've also disable windows firewall.

**Comment by joseph-henry** [comment]
Can you check that in your output for `zerotier-cli peers` that you have a `DIRECT` path between your nodes of interest? This sounds like you might be relaying.

**Comment by qt1** [comment]
I had a similar problem. I first changed MTU, which helped, but ended up moving away from ZT1 for that project.

I did work fine for about a year, but broke, I think sometime at 2021.

**Comment by PatrykW-95** [comment]
HI @joseph-henry. All the peers including planets and leafs are DIRECT. I've also tried changing MTU(2800,1500,100,68) in both  VMs as suggested by @qt1 and nothing changed.  There's samething else that I can try to resolve the problem?

**Comment by rhetr** [comment]
could this be related to https://github.com/zerotier/ZeroTierOne/issues/1422?

**Comment by joseph-henry** [comment]
> could this be related to #1422?

Maybe.

Just a shot in the dark, but we've recently fixed a bug that could cause some packets to fail their MAC (validation). This fix is available in `dev` and I'd be curious if it helps at all.

**Comment by myfingerhurt** [comment]
I found 1.8.x are not stable on my ac86u & ax86u, and 1.4.x never have these issues.
MTU sets to 1388, since the zerotier 1.4.x on router needed this to function normally.

1. Sometimes pings(ICMP) are OK from all peers and both sides, but TCPs are not, `zerotier-cli info` shows `ONLINE`, `listpeers` are all OK. Have to restart `zerotier-one` to get it fixed.
2. Sometimes `zerotier-cli info` went `OFFLINE`  and won't bring itself up, unless restarted  `zerotier-one` manually, the `zerotier-one -d` process was showing active but still `OFFLINE`. This problem has been seen since 1.6.x, but 1.8.x are becoming more frequent and significantly worse.

I Also found, 1.6.x/1.8.x on Windows 10 have performance issues when accessing the LAN IPs, for example my zerotier network is `10.9.8.0/24` and LAN is `192.168.9.0/24`, accessing emby server or RDP on my NAS `192.168.9.7` getting slower and slower, eventually I have to disconnect the zerotier, and instantly the network speed restores to normal.  The following is network topology.
`WIN10(10.9.8.8|192.168.9.8)<-->Router ax86u(10.9.8.4|192.168.9.1)<-->NAS_WIN10(192.168.9.7)`


Kernel:
`Linux RT-AX86U 4.1.52 #2 SMP PREEMPT Fri Mar 25 11:09:29 EDT 2022 aarch64 ASUSWRT-Merlin`

**Comment by rhetr** [comment]
> Just a shot in the dark, but we've recently fixed a bug that could cause some packets to fail their MAC (validation). This fix is available in `dev` and I'd be curious if it helps at all.

doesn't seem to help me

**Comment by joseph-henry** [comment]
Is anyone in this ticket still having issues? Since the creation of this ticket there have been two MTU-related fixes:

 - #1860 (will be in next release) lets you set the ethernet tap's overlay network MTU (default `2800`)
 - #1844 (will be in next release) lets you set the *Physical* MTU on a per-link basis using multipath. It will likely be generalized to work without multipath but you can try things like:
 
 ```
 {
  "settings":
  {
    "defaultBondingPolicy": "ab",
    "policies":
    {
      "ab":
      {
        "basePolicy": "active-backup",
        "failoverInterval": 30000,
        "links": {
          "eth0": { "mtu": 1400  }
        }
      }
    }
  }
}
```
Hopefully something can be of use. If you have further questions please let me know.
