### ISSUE TITLE
iphone wifi no upnp/nat-pmp requests no zt

### ISSUE THREAD

**Issue by MarkoPaasila** [zerotier/ZeroTierOne#1689]
Zerotieron iphone works perfectly over mobile/LTE, but not over wifi. Zerotier works as usual on computers in the same LAN both on ethernet and wifi. Only iphone doesn't work.

I reinstalled and reconfigured the zerotier one app on iphone.

My router runs openwrt 21.02 and miniupnpd. I have enabled both UPnP and NAT-PMP. Port forwards from other devices are shown, and the requests show up in the syslog. No request from iphone, nor any active port redirects.

`zerotier-cli peers` shows all other peers, just not the iphone when it's connected via wifi. Not direct, nor relayed.

iphone with ios 15.5
zerotier one version 1.8.10

**Comment by laduke** [comment]
Hello. It's possible/likely the ios app doesn't have an upnp client. The good news is upnp in not _required_ to make p2p connections.  Just outgoing udp and incoming/established udp. You might be able to do like `-A OUTPUT -p udp --sport 9993 -j ACCEPT` instead of all outgoing udp?  I'm not able to test at the moment.

**Comment by MarkoPaasila** [comment]
After more digging, it appears that the iphone indeed properly connects to the zt network while on wifi. My problem turns out to be that the iphone browser. It can't open zerotier addresses that are on the same subnet. Weird, but that's a different topic. I'll close this now since it doesn't turn out to be a problem.
