### ISSUE TITLE
How to use CLI directly in Android via TUN

### ISSUE THREAD

**Issue by Lua12138** [zerotier/ZeroTierOne#1715]
As ZerotierOne Android is not open source, I wanted to be able to use Zerotier via the CLI, so I did some experimentation.

I statically compiled the ARM executable via the cross-compilation toolchain and ran it on an Android 10 device (**using root**) with the following compilation parameters.

```
    make \
    ZT_STATIC=1 \
    ZT_DEBUG=1 \
    ZT_DEBUG_TRACE=1 \
    CC=arm-none-linux-gnueabihf-gcc \
    CXX=arm-none-linux-gnueabihf-g++ \
    CFLAGS="-Wall" \
    CXXFLAGS="-Wall" \
    LDFLAGS="-s" \
```

I then discovered that although the Android device was visible in the Zerotier Controller and the IP and version were correctly displayed, the corresponding IP and routing table was correctly displayed on the device via `ip ad` and `ip route`. However, it was not actually possible to communicate.

This log output is available on Android:

```
requesting configuration for network <NETWORK_ID>
learned new path 47.254.39.171/9993 to 451e1bcd2d (packet 83c94f7455245fc1 local socket 24751240 network 0000000000000000)
learned new path 47.254.39.171/9993 to 451e1bcd2d (packet 27f78687dc532c4c local socket 24752072 network 0000000000000000)
learned new path 47.254.39.171/9993 to 451e1bcd2d (packet 3aace22563cf24c1 local socket 24761048 network 0000000000000000)
learned new path 84.17.53.155/9993 to cafe04eba9 (packet 6206803e3b771efa local socket 24751240 network 0000000000000000)
learned new path 50.7.252.138/9993 to 62f865ae71 (packet 62067fb9b5119d9a local socket 24752072 network 0000000000000000)
learned new path 104.194.8.134/9993 to cafe9efeb9 (packet 62965da8502523c5 local socket 24751240 network 0000000000000000)
trying unknown path 104.194.8.134/9993 to cafe9efeb9 (packet 62965da85025b36f verb 5 local socket 24761048 network 0000000000000000)
requesting configuration for network <NETWORK_ID>
learned new path 103.195.103.66/9993 to 778cde7190 (packet 624f26cab7985461 local socket 24761048 network 0000000000000000)
trying unknown path <MY_ID>/30356 to f4b7f79a0a (packet 5fd54282b47ffaab verb 8 local socket 24761048 network 0000000000000000)
trying unknown path <MY_ID>/30356 to f4b7f79a0a (packet 9350ccb5c20f1429 verb 8 local socket 24751240 network 0000000000000000)
trying unknown path <MY_ID>/30356 to f4b7f79a0a (packet b7cb5f1fc6e0c571 verb 8 local socket 24752072 network 0000000000000000)
learned new path 84.17.53.155/9993 to cafe04eba9 (packet 6206803e3bb32355 local socket 24752072 network 0000000000000000)
trying unknown path 104.194.8.134/9993 to cafe9efeb9 (packet 62965da85094d197 verb 5 local socket 24761048 network 0000000000000000)
trying unknown path 104.194.8.134/9993 to cafe9efeb9 (packet 62965da850bbe285 verb 5 local socket 24761048 network 0000000000000000)
trying unknown path <MY_ID>/30356 to f4b7f79a0a (packet 2592f42b345e677b verb 8 local socket 24761048 network 0000000000000000)
trying unknown path <MY_ID>/30356 to f4b7f79a0a (packet c3430f29f87d3b50 verb 8 local socket 24751240 network 0000000000000000)
```

I checked the [AOSP code][1] and found no significant differences from Zerotier.

I'm not sure if it has anything to do with [this method][2], which is [called here at NDK][3].

[1]:https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/jni/com_android_server_connectivity_Vpn.cpp;l=58;drc=38898882788358f6ae26de987e1346597366d2f7
[2]:https://developer.android.com/reference/android/net/VpnService#protect(int)
[3]:https://cs.android.com/android/platform/superproject/+/master:system/netd/client/NetdClient.cpp;l=490;drc=422de9d1d0e325ccd4e911c6c446d2feb1f7c33a

**Comment by glimberg** [comment]
You are correct that the full Android app does not have a CLI as it's not part of that apk whatsoever.  It's a version of the core ZeroTier code wrapped via JNI to expose it to the Java ecosystem on Android and the CLI is not part of it.

To put it simply, Android is its own beast and I have no clue if zerotier will even work on it in this manner.  At the very least, it requires a kernel with the tun/tap module available and installed.  And even then, you'll have to have a rooted device to begin with, which very few people have in the grand scheme of things.  You're free to continue hacking on this if you wish, but in house we have no rooted Android devices, nor the experience with them to help.  There's next to 0 customer demand for it either, so it's not something on our priority list.

**Comment by Lua12138** [comment]
I know that Zerotier Android does not include a CLI because it is unnecessary for the user.

I have some IoT Android devices here and the user cannot actively configure Zerotier, so the CLI tool is available at the time of production of the device and has root.

But Zerotier Android is not open source and I have no way to get inspiration from it. One can only try to port the Linux version to Android, although the results are always uneventful.

Everything seems to be working, but the packets are not getting out. So I guess there are two possibilities, one is that the VpnService.protect method is not called, as in Android, and the other is that there is a problem with the routing table.

As you say, the [JNI Wrapper][1] does not include the Zerotier Core, and again I cannot build my own CLI through this.

[1]:https://github.com/zerotier/ZeroTierOne/tree/master/java

**Comment by glimberg** [comment]
it *does* include the ZeroTier core. Here's the NDK build stuff for it.  The NDK code for it is here:  https://github.com/zerotier/ZeroTierOne/tree/master/java/jni. This just wraps the code the [node](https://github.com/zerotier/ZeroTierOne/tree/master/node) directory though and is not the full service whatsoever.  It does no network communication on its own.  It probably won't help you much

**Comment by Lua12138** [comment]
thanks a lot.

**Comment by cinit** [comment]
Hi @Lua12138, sorry for my late and unsolicited comment. I have been using zerotier-one CLI on Android with root privilege for several days and I hope my comment will be helpful for those who want to run ZeroTier on Android with root, typically for running alone with other privilege tunnels or joining multiple networks.

Android uses the routing policy database (RPDB) to route the application's IP packets. It has its own routing policy and it doesn't rely on the traditional main route table (whose table ID is 254). You can check that by running the `ip rule` and `ip route show table all` commands. If you are not familiar with iproute2, you may want to read https://manpages.ubuntu.com/manpages/focal/en/man8/ip-rule.8.html.

As you mentioned above, the `VpnService.protect(int fd)` method sets a correct fwmark on a socket, such that the socket will bypass a VPN tunnel. If you are not using zerotier-one together with other VpnService, you do not need to call `VpnService.protect(int fd)`, because there are no other VPN tunnels.

When zerotier-one starts with root privilege on Android, it will create TAP tunnels, connect to planets and other peers, and set an IP address on its interface, except add a rule into the routing policy database, and that's all you need to do when you try to run ZeroTier CLI on Android.

The routing rule preference constants used by the Android system can be found at https://cs.android.com/android/platform/superproject/main/+/main:system/netd/server/RouteController.h and you can check whether it's consistent with the output of the `ip rule` command on your Android. After that, pick a route table to add the ZeroTier TAP interface into it by `ip route add table $your_selected_table_id $cide/$prefix dev $zt_iface_name proto kernel scope link` and ZeroTier should work on your Android now.

**Comment by Lua12138** [comment]
Thank you @cinit  very much for your reply.

But after I tried each table id separately, I still couldn't connect. Which table id should I choose?

I tried every table id with this:

```ash
i=10000
while [ $i -le 32000 ]
do
  echo "table id:$i"
  ip route add table $i 10.0.1.0/24 dev ztyvvzal2p proto kernel scope link
  sleep 60s
  ip route del table $i 10.0.1.0/24 dev ztyvvzal2p proto kernel scope link
  i=`expr $i + 1000`
done

```

**Comment by cinit** [comment]
Hi @Lua12138.
It seems you are mistakenly using rule preferences as table ids.
The range [10000, 32000] is for rule preferences, not table ids.
Please read [ip-rule manual](https://manpages.ubuntu.com/manpages/focal/en/man8/ip-rule.8.html) carefully.

**Comment by Lua12138** [comment]
Thank you again @cinit , it was indeed a cheap mistake on my part, and as per your guidelines, the Zerotier is now working fine.

Also I changed some code in ZT and now it works without me having to set the `ip` command manually.

**Comment by xyxyxoxo** [comment]
> Also I changed some code in ZT and now it works without me having to set the `ip` command manually.

@Lua12138 I'm trying to achieve the same thing. Could you share the patch you made that makes things work without invoking the `ip` command?
