### ISSUE TITLE
Update multipath / bonding documentation to match reality

### ISSUE THREAD

**Issue by grapexy** [zerotier/ZeroTierOne#1745]
From a week or two of testing ZT multipath, I've learned that following documentation will often lead to many hours of debugging, only to discover that docs were wrong.

[Multipath](https://docs.zerotier.com/zerotier/multipath/) page full of errors. Including outdated enum naming, documenting not currently implemented functionality without a proper disclaimer, documenting sample settings that are outright wrong to name a few. This should be properly updated to fix these issues.

Several issues that I've noticed:

1. Usage of built-in policy names for custom policies:
```
{
  "settings":
  {
    "defaultBondingPolicy": "balance-aware",
    "policies":
    {
      "balance-aware":
      {
        "basePolicy": "balance-aware",
      }
    }
  }
}
```
This will result in error:
`error: custom policy balance-aware will be ignored, cannot use standard policy names for custom policies`

2. Docs are using `quality` key for link quality weights, but ZT expects `qualityWeights`.
3. `balancePolicy` for `balance-aware` does not appear to be used anywhere. I.e. packet-based load-balancing is not currently implemented.
4. I may be wrong on this, but it doesn't look like link speed is taken into account for path selection at all.

In some cases, it's not clear if it's the docs that are wrong, or zt-one, so it would be nice to shine some light on the state of multipath in general. At the very least, I think it's critical to properly label or remove currently unimplemented functionality from the docs.

**Comment by joseph-henry** [comment]
@grapexy Thanks again for your PR as well as general testing. There's some [new documentation](https://docs.zerotier.com/zerotier/multipath) that reflects new updates to the `dev` branch. There's still some more work in the pipeline but things should match up a little more closely now. To answer your questions:

1) This is by design. We only wanted custom behavior for non-standard policies since one might re-use a standard policy elsewhere in the config file. So, any time you tweak a parameter it'll need to be a different name.

2) This has now been fixed and is `linkQuality`. The `balance-aware` section has an [example](https://docs.zerotier.com/zerotier/multipath#balance-aware)

3) This was because `balance-aware` proved unstable in its earliest implementation and was temporarily removed. An updated implementation is now included. 

4) Correct. This was part of the `-aware` portion that was removed. It is now re-added as `capacity` and is used to hint to ZeroTier the "diameter of the pipe" in a vague sense. This will result in proportional allocation now.

Let me know if you find any other issues. There's a few more fixes that'll trickle in over the next week or so before this is included in a proper release but for now you can build from the `dev` branch with `ZT_DEBUG=1 and ZT_TRACE=1` for a lot of useful diagnostic info.

**Comment by grapexy** [comment]
@joseph-henry Awesome. Thank you! 

I'm testing dev branch now, but ZT freezes on FreeBSD peer right after `balance-aware` bond is built. Linux peer is fine and this seems to only be related to `balance-aware`. Logs don't show anything useful, they just cut at the point of freeze.

I'll do some more digging and report if I find anything useful. Thanks again!

**Comment by joseph-henry** [comment]
Ok good to know. Haven't tested on FreeBSD yet. I'll still address your other performance ticket in time. Feel free to open others if you find new problems.
