### ISSUE TITLE
Network Controller Backwards Compatibility

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#190]
v1.0.3 nodes does not seem to work on v1.0.2 network controllers. We host some networks on the public controller on zerotier.com, but prefer our own network controller for reliability and security aspects for some of our other in-house networks. 

Problem:
v1.0.3 nodes are stuck at message: "REQUESTING_CONFIGURATION".

Steps to Reproduce:
Upgrade a v1.0.2 node to version v1.0.3 (while keeping existing v1.0.2 network controller).

As a side note, we trust redis more than sqlite, as its simplicity and reliability has led to widespread use within our organization.

**Comment by adamierymenko** [comment]
The hosted network controller still runs the old version, since the new one from 1.0.3 is not heavily tested. Are 1.0.3 and older versions running side by side here -- in other words, are 1.0.1/2 versions able to get configurations while 1.0.3 is not?

**Comment by heri16** [comment]
Yes, v1.0.2 is able to get configuration while 1.0.3 fails. Could it be a database schema issue or something else?

**Comment by heri16** [comment]
Apologies for the false alarm. We were using the old v0.9.7 on the netconf-master, which is not compatible with v1.0.3.

**Comment by adamierymenko** [comment]
hah... thanks! I was really scratching my head about this one since the web site still uses the old nodeJS controller. :smirk_cat:

**Comment by heri16** [comment]
What is the rationale for a redesigned network controller based on sqlite?

**Comment by adamierymenko** [comment]
Three reasons:

 1. Make it a self-contained easy to deploy micro service with few moving parts. (JSON API also fits into this)
 2. Make it small so it could run in a small device -- future on-premise device product ideas, etc.
 3. Make it faster -- the multiple moving parts and nodeJS version is too slow to scale.

The first point is probably the biggest one, since it also means it's trivial to deploy and we can scale horizontally more easily. I loathe "rube goldberg machine" software with multiple moving parts.

It made sense to code the first version in Node since it's quicker to write, but now that we know what we're doing it makes sense to do a 'harder' version in native code.

**Comment by heri16** [comment]
Native code is fine, but why sqlite? It has marginally worse performance than redis. Seems like going backwards.
