### ISSUE TITLE
ZeroTier overrides default route without being configured to

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [zerotier/ZeroTierOne#2002]
Happening on: zerotier-one   1.10.6 debian package
What I expect: ZeroTier only generates an interface on my machine with the subnet I specified on my account

What I get (`route -n` output):
```Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         0.0.0.0         255.255.255.255 UH    0      0        0 zt2lr7xjrf
0.0.0.0         0.0.0.0         0.0.0.0         U     0      0        0 zt2lr7xjrf
169.254.0.0     0.0.0.0         255.255.0.0     U     0      0        0 zt2lr7xjrf
192.168.1.0     0.0.0.0         255.255.255.0   U     600    0        0 wlan0
192.168.1.0     0.0.0.0         255.255.255.0   U     3003   0        0 wlan0
192.168.1.1     0.0.0.0         255.255.255.255 UH    0      0        0 wlan0
192.168.80.0    0.0.0.0         255.255.255.0   U     0      0        0 zt2lr7xjrf
```

I should ONLY see the last route pointing to the subnet specified on my account

- Why did it delete my default route directing the traffic on `wlan0`?
- Why did it set a default route for his interface?
- What's that weird subnet I never specified anywhere (`169.254.0.0`) coming up under the global one generated by zerotier?

**Comment by atleta** [comment]
This happens to me too. I suspect it happens if/when the original interface with the default route (in your case must be wlan0) goes down and/or the network becomes unavailable. (At least, for me it's happening after my router goes offline. I have experienced losing acces to the internet/WAN after short internet outages. I thought it was my router but realized yesterday that the routing table has changed.)

And of course, it won't work because zerotier itself would need WAN access to work or at least routing table entries that let it access the peers + zerotier servers.

**Comment by laduke** [comment]
It looks like something else on your system is trying to manage your zerotier interfaces. 
Steps to reproduce would be very helpful!

**Comment by raku-cat** [comment]
Was just about to open a report for this, I'm getting this on my system as well.

Some system info:

- OS: Arch Linux
- Kernel: Linux 6.2.13-arch1-1 
- ZeroTier Version: 1.10.6
- Network Management done by systemd-networkd (switched recently which is how I encountered this bug) and also with Intel Connman to manage systemd-networkd, via cmst.  My wireless interface does have it's own configuration file in /etc/systemd/network/25-wireless.network
- Connecting to internet via wifi

I encounter this problem specifically when resuming from suspend, general usage doesn't seem to give me any issue that I've found as of yet, which would line up with this report's reasoning, the wireless interface takes some time to establish a link while resuming, so the system defaults to the first available interface, the zerotier one.

Steps to reproduce:

1. Start with a powered on system, connected to wifi, managed via systemd-networkd.
2. ZeroTier is started, and works fine, no disruption to internet connection caused either, no problems yet.
3. System is placed in to suspend, and left for some time. (while troubleshooting this before, I attempted to suspend and then immediately resume, since I usually encountered this coming back to my PC I didn't really associate specifically a "timeout" with it, I'm assuming this is maybe the lease on the router expiring or the wifi adapter becoming unpowered after a while of the system being suspended, thought it worth mentioning though if you have trouble reproducing this)
4. Resume from suspend and observe no networks aside from my local lan are reachable.
5. Observe routing table output as follows, note the default device is the zerotier one:
```
default dev ztXXXXXXXX scope link 
default via 192.168.1.50 dev wlp3s0 proto dhcp src 192.168.1.10 metric 1024 
169.254.0.0/16 dev ztXXXXXXXX proto kernel scope link src 169.254.72.20 
192.168.1.0/24 dev wlp3s0 proto kernel scope link src 192.168.1.10 metric 1024 
192.168.1.50 dev wlp3s0 scope link 
192.168.1.50 dev wlp3s0 proto dhcp scope link src 192.168.1.10 metric 1024 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown 
192.168.254.0/24 dev virbr1 proto kernel scope link src 192.168.254.1 linkdown 
```
6. In this step, I have a bit of a knowledge shortage to explain what I'm doing here.  Within cmst There's a display as below:
![image](https://github.com/zerotier/ZeroTierOne/assets/1125449/b5ec18ed-496f-4879-b575-8ad5324b1e1a)
I change the "powered" on "wired" to off, and then back on, though I believe powering it off is enough to fix the issue, though obviously stops ZeroTier from functioning.
7. Observe internet now working, routing table output as follows, default route and device is the wireless adapter:
```
default via 192.168.1.50 dev wlp3s0 
default via 192.168.1.50 dev wlp3s0 proto dhcp src 192.168.1.10 metric 1024 
x.x.x.x via 192.168.1.50 dev wlp3s0 
192.168.1.0/24 dev wlp3s0 proto kernel scope link src 192.168.1.10 metric 1024 
192.168.1.50 dev wlp3s0 scope link 
192.168.1.50 dev wlp3s0 proto dhcp scope link src 192.168.1.10 metric 1024 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown 
192.168.254.0/24 dev virbr1 proto kernel scope link src 192.168.254.1 linkdown 
```

Hopefully this gives a clearer picture! I can also note, prior to this I was using NetworkManager + nm-applet, all the above actions (leaving zerotier running, suspending my system, returning to it and resuming) would not cause this issue, so I'm inclined to believe it may be an issue of systemd-networkd + zerotier?

**Comment by laduke** [comment]
Thanks! 
Try making a file like this:

```
/etc/systemd/network# cat 99-zt.network 
[Match]
Name=zt*

[Link]
Unmanaged=Yes
```

I haven't tested, so it might be slightly off. You'll have to figure out how to make systemd reload network config (or just reboot) 

https://www.freedesktop.org/software/systemd/man/systemd.network.html

You could also search `dmesg` or `journalctl` for clues. 

`169.254.0.0/16 dev ztXXXXXXXX proto kernel scope link src 169.254.72.20 `, for example, means something is trying to do dhcp on that interface and failing. 
There is no dhcp server on the network (and IIRC dhcp is blocked on purpose in the zerotier client)

**Comment by raku-cat** [comment]
Yup, could also use `GatewayOnLink=false` in the `[Network]` section of a configuration file, I didn't realize you could widlcard match interfaces like that though which is what ultimately lead me here, having to work around this in systemd's configuration was less than ideal to me, this seems like sort of a happy medium however. 
Though, admittedly I'd most prefer a solution that works more transparently (i.e., doesn't require me to adjust such configs) if possible, as it seemed more like a bug in ZeroTier than a quirk to account for, I suppose this may just be an edge case that had yet to be encountered, and me and OP's recent finding of this problem was just a coincidence lol. 
In either case I'll do some troubleshooting to see what systemd configs will play nicely and report back here.

**Comment by laduke** [comment]
Yeah. Definitely don't want everyone to need to figure that out. I'm sure zerotier could create that file, but it doesn't seem quite right. 

Maybe some in networkd changed recently. I haven't seen this, but I don't have a machine using networkd that also sleeps.

**Comment by raku-cat** [comment]
Back with some new info :) 
So I have the following config now, same as yours:
```
/etc/systemd/network/99-zt.network 
[Match]
Name=zt*

[Link]
Unmanaged=Yes
```
This didn't seem to make any difference on resuming from suspend. I have found however, that restarting zerotier after resuming rather than my charade within csmt is also effective, if that helps with any reproducing the issue with less software dependencies.
I'm starting to be more convinced this is either a bug in ZeroTier or an undiscovered odd interaction between it and systemd-networkd, I think as a temp workaround maybe something with a hook could be done similar to below?
```
[Unit]
Description=Reset Default Route after Suspend
Before=network.target
StopWhenUnneeded=true

[Service]
ExecStart=<command to restart zerotier or similar>

[Install]
WantedBy=suspend.target
```
I'll troubleshoot more of these workaround in the meantime and report back.

**Comment by laduke** [comment]
Thanks again. Does this thread seem relevant? https://github.com/systemd/systemd/issues/26665#issuecomment-1454353725 


These two settings seem interesting:

https://www.freedesktop.org/software/systemd/man/networkd.conf.html#%5BNetwork%5D%20Section%20Options

> ManageForeignRoutingPolicyRules=
A boolean. When true, systemd-networkd will remove rules that are not configured in .network files (except for rules with protocol "kernel"). When false, it will not remove any foreign rules, keeping them even if they are not configured in a .network file. Defaults to yes. 


> ManageForeignRoutes=
A boolean. When true, systemd-networkd will remove routes that are not configured in .network files (except for routes with protocol "kernel", "dhcp" when KeepConfiguration= is true or "dhcp", and "static" when KeepConfiguration= is true or "static"). When false, it will not remove any foreign routes, keeping them even if they are not configured in a .network file. Defaults to yes.


haven't been able to set up to reproduce myself yet, sorry

**Comment by raku-cat** [comment]
Appreciate all your research on this matter :) Will take some time to test all those options and see if they help. 
I will note, something I didn't provide in my initial comment about my environment, I only have two systemd network configuration file:
```
$ ls /etc/systemd/network
25-wireless.network   99-zt.network
```
 One is  for my wireless adapter, and the one catchall zt interface one which I only created after your suggestions, so I believe any of the options which indicate a default that we would be setting anyway, or that certain behavior would be occurring when no matching config file is found, applies to me, as this issue occurred/occurs even with no config file for the zt interfaces.

In the meantime I've figured out a bit of a hack solution which I've found to so far work consistently, definitely not ideal for everyone though.
```
/etc/systemd/system/reset-zerotier.service
---
[Unit]
Description=Reset ZeroTier One after Suspend
Before=network.target
StopWhenUnneeded=true

[Service]
Type=oneshot
ExecStart=/usr/bin/sh -c "sleep 10 && /usr/bin/systemctl is-active --quiet zerotier-one.service && /usr/bin/systemctl restart zerotier-one.service"

[Install]
WantedBy=suspend.target
```

Note I have a piece in my command to fail if the zerotier service wasn't already running, my usecase for zerotier is I start it up when I need it and tend to leave it running, but I don't have the unit enabled, thus I have no need for it to be restarted if the service wasn't already running.

**Comment by raku-cat** [comment]
Another update:

Have done some continued testing on this throughout the past couple days, based on some of my own searching I came to the same conclusions as you, those two options seem like likely solutions, I've tried all of them but unfortunately none work.
`ManageForeignRoutes=no` actually breaks internet completely while zerotier is enabled outright, or it's at least very shoddy, i could get maybe 1 or 2 pings to go through but it seemed like some process would kick off shortly after systemd-networkd was restarted and would eventually permanently disrupt traffic flow.
My above unit file for restarting zerotier after resume has given me the most consistent successes, I'm going to continue to test though, I do feel like we're on the right path for finding a systemd side solution to this.


On a related note, in reading your linked GH issue comment, while I was reading the rest of the thread, I noted the user was receiving actual lines in their journal like so:
```
Mar 04 04:08:57 Elitebook systemd-networkd[328]: Removing foreign routing policy rule (configured,marked): priority: 32764, 0.0.0.0/0 -> 0.0.0.0/0, iif: n/a, oif: n/a, table: main(25
```
I don't get any such lines which mention a foreign routing policy:
```
user ~ $ journalctl | grep foreign
user ~$
```
My thinking is perhaps the "fix" on zerotier's side of this would be to have their routes be foreign policy routes? I may be talking gibberish here, my understanding of these things is very limited, but from my testing it seems setting `ManageForeignRoutingPolicyRules` to no did nothing, and since I have no foreign routes anyway, this makes sense, perhaps if zerotier made them as such this fix would work?  Not entirely sure what the butterfly effects would be. 
Either way the commit they linked in my opinion is almost certainly the smoking gun https://github.com/systemd/systemd/commit/a39a9ac8065c29330207838b70fe388bde2bc254  
Since interfaces are reconfigured on resume and zerotier interfaces are the only ones that would be active, it makes sense they would become default, so knowing that, hopefully this can help with further research on this issue.

**Comment by laduke** [comment]
@TanyaEleventhGoddess What version of debian and systemd are you seeing this on?

**Comment by laduke** [comment]
I can't reproduce on an arch vm with systemd 253. suspend might work differently than on your real hardware.

**Comment by raku-cat** [comment]
I'm back with results!
This took a while to realize after staring at log entries for a bit, but noticing that even with a log level of debug i had barely any log lines at all... I realized it was connman doing it!
I'll spare the process it took to figure this out, but after disabling `connman.service` and `connman-vpn.service`(this ones important, the actual culprit) on my system, things are back to normal, no issues at all! 
So then it would seem, maybe there's a bug between ZeroTier and Connman? Not quite, I immediately started researching this, and the pieces immediately fit, see this below thread:
https://forum.libreelec.tv/thread/26221-wireguard-with-both-eth0-and-wlan0-enabled-seems-like-wireguard-tunnel-goes-thro/
This person ends up with the identical routing issue to me, which is there vpn devices getting set as the default dev, and it seems to be an issue with connman that has yet to be resolved :(

**Comment by laduke** [comment]
Thanks for doing all that debugging! 
I hope this helps other people with similar issues.

**Comment by laduke** [comment]
You might be able to blacklist zt interfaces
https://wiki.archlinux.org/title/ConnMan#Tips_and_tricks
