### ISSUE TITLE
Please update the precompiled version of zerotier for ds216play

### ISSUE THREAD

**Issue by snachx** [zerotier/ZeroTierOne#2044]
The precompiled version of Zerotier for ds216play with DSM 6.2.4 is stuck at 1.4.0. I hope it can be updated to 1.4.6, as this version seems to fix the issue of failing to add routes in Linux. If you don't have the time to do this, where can I find instructions for compiling early versions into Synology packages？

**Comment by joseph-henry** [comment]
Unfortunately we won't be issuing new updates to the DSM6 package due to the age of various compiler toolchains needed to build for that target.

The best thing I can think of if you really need DSM6 support is to look at the SynoCommunity repos, and specifically this older effort: https://github.com/SynoCommunity/spksrc/pull/3458

I wish you luck!
