### ISSUE TITLE
ZeroTier takes 4 mins to realize I am online

### ISSUE THREAD

**Issue by cyph84** [zerotier/ZeroTierOne#2051]
If zerotier 1.10.6 is started before my interface gets a DHCP lease it logs ```zerotier-one[302]: sendto: Network is unreachable```.  zerotier is then in ```OFFLINE``` state.

After my interface is configured, it takes about 4 minutes before it realizes network is online and moves to ```ONLINE``` state.

zerotier 1.8.10 did that in about 1 minute.

**Comment by xaksh** [comment]
Hi @cyph84,

We are using zerotier on Ubuntu 20.04 and have realized that it was using `network-online.target` in the systemd service for `After` and `Wants` check.

Since we were using network-manager, the network-online.target was not reporting the system being online accurately and hence we changed the `Wants` and `After` check to `NetworkManager-wait-online.service`. This has resolved the issue for us for time being.

**Comment by laduke** [comment]
should be fixed in 1.12.1!
