### ISSUE TITLE
Multipath -- multiple active Paths at any given time

### ISSUE THREAD

**Issue by maci0** [zerotier/ZeroTierOne#210]
Hi,

is there any mechanism in place to handle tunnels over multiple paths?
For example I have an Ethernet connection in one network, a WiFi connection over another network and a 3G connection.
In theory all of them could reach the target node. 
It would be good if ZT1 would transparently use the path with the smallest RTT and automatically uses another path if one fails. Something similar has been achieved in for another UDP application (mosh) http://arxiv.org/pdf/1502.02402.pdf

Just an idea. Might be worth evaluating, especially when its common that people connect on their home WiFi, take their phone and walk out etc..

**Comment by adamierymenko** [comment]
The protocol technically supports this -- since it uses cryptography to validate the authenticity of packets, the physical port on which a packet arrives is irrelevant. The code simply doesn't support this yet. So far the focus has been toward maximally-reliable performance over a single optimal path.

Once we get all the final edge cases and kinks worked out there, this is probably a next step.

**Comment by heri16** [comment]
I think this would also make sense if multiple default gateways are issued by a single DHCP server response (which Windows will happily accept on a single network interface).

**Comment by heri16** [comment]
I tested out the failover of peer paths from public ip to private ip (across subnets) and backwards. It seems to be super slow just to detect that the underlying network has recovered. I think we need multipath asap.

**Comment by adamierymenko** [comment]
Multi path would help, but what we really need is to implement some better path heuristics to detect connectivity shifts. It's possible but it has to be done carefully. The problem is that if care isn't taken you create a denial of service vector -- if you just trust any information about your connection from other peers and use it to make connection reset decisions, a random peer can send you carefully crafted messages and force your connection to reset over and over. Right now we err on the side of caution but it could be improved.

**Comment by adamierymenko** [comment]
If something in ZT's design seems like it could be done better or more aggressively but it isn't, the answer may be 'DOS resistance' or some other security concern.

**Comment by adamierymenko** [comment]
Basically any time we make a peer trust *any* information from *anyone*, we have to think long and hard about all the possible implications of that.

**Comment by mikebutash** [comment]
Perhaps use something like Dead-Peer Detection like ipsec can use?  Basic keepalive protocol really ala routing protocol with controllable timers is all that is needed, but if using on a local lan for production data centers, consideration of faster detection like Bi-directional Forwarding Detection would be nice too ultimately.

Multipath seems good in theory with the state of transitive mobile devices, but until then as said, failover detection (and mitigation) is a better start to that fix first I'd say in any regard.

**Comment by travismorton** [comment]
I'm testing this out right now, but using the latest `dev` branch results in a segfault when `local.conf` is using any `multipathMode` other than 0. Before commit https://github.com/zerotier/ZeroTierOne/commit/270debb3fc39c3f1f6a3f6fbc2c5fb6183182c8f it won't segfault, however `zerotier-cli -j status` returns null status for multipath and only sends traffic over one interface (with either multipath mode 1 or 2). Both machines I'm testing with have two interfaces with a public address on each. Looking at the `/peer` API endpoint, each machine can see two paths to the other.

Building on linux with
* GCC 7.3.1
* make 3.82
* kernel 4.14.97

If this should be its own issue or broken into separate issues, please let me know and I'll separate them out.

**Comment by joseph-henry** [comment]
Did you set `ZT_PROTO_VERSION` in `node/Packet.hpp` to `10`?

**Comment by travismorton** [comment]
That did it, thanks! I glossed over that, sorry about the noise.

**Comment by adamierymenko** [comment]
Done in 1.4
