### ISSUE TITLE
Java build for sockets library is broken due to submodule errors

### ISSUE THREAD

**Issue by tejas238** [zerotier/ZeroTierOne#2195]
I had initially opened this issue in the libzt repository but since the error is related to modules in this library, I was suggested to report here.

I'm trying to build the ZeroTier sockets java library on orangepi zero (armv7l architecture) but keep getting internal compiler errors for targets 'CMakeFiles/zto_pic.dir/ext/ZeroTierOne/node/Bond.cpp.o' and 'CMakeFiles/zto_pic.dir/ext/ZeroTierOne/node/CertificateOfMembership.cpp.o'. Log file is attached.

[libzt-java-log.txt](https://github.com/zerotier/libzt/files/13693263/libzt-java-log.txt)

I've already tried building on the following configurations to no avail:

Ubuntu 16.04 (Xenial), openjdk-17-jdk, cmake 3.26.6, gcc compiler 6.5
Ubuntu 16.04 (Xenial), openjdk-11-jdk, cmake 3.26.6, gcc compiler 5.4.0
Debian 9 (Stretch), openjdk-11-jdk, cmake 3.18.4, gcc compiler 10.2.1
Debian 11 (Bullseye), openjdk-11-jdk, cmake 3.18.4, gcc compiler 10.2.1

Which OS/java/cmake/gcc versions are currently working/compatible for orangepi 0 architecture? I had previously built successfully in Nov 2022 on the Debian 9 configuration but haven't been able to since then.

Thanks, any suggestions will be greatly appreciated!

**Comment by joseph-henry** [comment]
> c++: internal compiler error: Killed (program cc1plus)

Hmm. This looks suspiciously like a faulty SD card and the compiler trying to read a bad source file. The only times I've seen this error were in times where my repo was corrupted due to my own antics or an issue with the filesystem.

I could be far off here. But my general rule for Pi's and the like is to make sure my SD card is much bigger than I really need (like 10X) to keep wear leveling reasonable and also to buy known brand names from their shops and not Amazon or eBay.

Let me know if that doesn't help.

**Comment by tejas238** [comment]
Thanks, this does sound like a possible root cause. I had to reflash the OS on the sd card multiple times in the past due to booting issues. This could also be the cause of the other issue I had raised about multithreading. 

Thanks a lot, will check it out and update here if it solves the problem.

**Comment by tejas238** [comment]
@joseph-henry After many months of debugging on and off, it turned out to be an issue with the board itself I was using. On  a new board, everyhing's fine. Thanks for the suggestion!
