### ISSUE TITLE
Could zerotier be used behind a socks5 proxy?

### ISSUE THREAD

**Issue by pandada8** [zerotier/ZeroTierOne#226]
the access to the internet is limited and i have an avaliable socks5 proxy?
could the zerotier using an socks5 to forward?
the platform is Mac OS X and using proxifier to make the socks5 globally

**Comment by adamierymenko** [comment]
It would be possible to run the service inside proxifier as long as it leaves convention file descriptors (like this used to open tap devices) alone. But it would probably be slow.

**Comment by alxTools** [comment]
yes you can, i just did it
![faf51cf94ef8cad99410b1a8d1030ab2a1dd5b946b54e0716af83bfa67d7e142](https://github.com/zerotier/ZeroTierOne/assets/40523587/e9ab7087-a806-4f9c-8808-05e8d8e71765)
![19078605fa8060fe7574f8a1eb61de5119fefb42e7a82cd6b894da47b3b464f0](https://github.com/zerotier/ZeroTierOne/assets/40523587/4c8267a6-43c6-45e4-9e5d-06a718058334)

i also had to set the default route to be the proxy too, because it was randomly sending and receiving packets from the proxy and from direct connection, now everything working.
