### ISSUE TITLE
Fails to compile with rust 1.80.1

### ISSUE THREAD

**Issue by r-vdp** [zerotier/ZeroTierOne#2345]
The latest release fails to compile with rust 1.80.

I think we probably need to update the rust dependencies and cut a new release.

**Comment by glimberg** [comment]
Seems to be building fine over here.  What error are you getting?  What platform are you on?

**Comment by stradiot** [comment]
Hello,
the issue seems to be with the `time` dependency in version 0.3.34.

It is already resolved in version 0.3.36: https://github.com/time-rs/time/issues/693.

<img width="1322" alt="image" src="https://github.com/user-attachments/assets/1f3ee287-017a-462b-aa89-2b2c1f39b21f">

My platform: Debian bookworm aarch64.

**Comment by r-vdp** [comment]
Yeah, same error here, sorry for not including it in the first message.

**Comment by leleobhz** [comment]
Hello!

I confirm the update to time 0.3.36 fixes compilation issue over stable 1.14 and I've applied it to my Zerotier Docker images: https://github.com/ZenithTecnologia/zerotier-docker/blob/main/patches/1.14.0-cargo-time-version.patch

**Comment by glimberg** [comment]
Send a PR here and we can get it merged

**Comment by adamierymenko** [comment]
Fixed in 1.14.1, going out in a few.
