### ISSUE TITLE
Consistent network interface naming

### ISSUE THREAD

**Issue by bonki** [zerotier/ZeroTierOne#256]
I have two questions regarding the above:

1. Why does the BSD implementation first create a `tapXXXX` device and then try to rename it to its deterministic name? It seems more logical to me to try to create the device with its deterministic name first and if that fails fallback to using `tapXXXX` (and skip trying to rename things altogether).

2. Why don't we do the same on Linux (and possibly OSX) and get rid of `devicemap` there as well? Even though [device renaming seems ~~broken~~unsupported on Linux](https://www.kernel.org/doc/htmldocs/device-drivers/API-device-rename.html) I don't see why we can't create the device with its deterministic name directly (same as in (1)). I just tried and adapted `osdep/LinuxEthernetTap.cpp` accordingly to use the same base32hex naming scheme and it works as intended. I am hesitant to submit a pull request though since I fear I might be missing an obvious show-stopper here?

As an aside, the maximum length of network interface names (`IFNAMSIZ`) appears to be the same on all of [Linux](http://lxr.free-electrons.com/source/include/uapi/linux/if.h?v=3.19#L26), [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=netintro&apropos=0&sektion=4&manpath=FreeBSD+11-current&arch=default&format=html#INTERFACES) and [OSX](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man4/netintro.4.html), namely `15` characters. Too bad the network ID doesn't fit in there without re-encoding :/

**Comment by janjaapbos** [comment]
I actually use devicemap to change the name of a zt device in something I like to refer to. That works quite well (you have to leave & join to get the new name active). Also, if you populate devicemap with the preferred name mapping beforehand, the client will use the specified name on the first join.

**Comment by bonki** [comment]
Good point; I see how being able to manually populate `devicemap` can be desirable. However, on BSD `devicemap` isn't currently used at all so right now behavior is different across systems and quite unnecessarily so. Consistent device names are definitely desirable, but I agree that it should be possible to map them (in which case this needs to be added to the BSD implementation).

**Comment by adamierymenko** [comment]
Yes, and the other problem is that OSes (even within the same family like BSD) differ substantially on issues like how long a name can be and what characters can be in it. I used the programmatically-specified naming scheme on FreeBSD because it appears to allow renaming of devices to those long names. But Linux doesn't seem to allow this, and OS X is extremely strict. On OS X devices can only have the names their driver initially registers and renaming is not supported.

It would be nice if there could be a consistent naming scheme, but I don't think it's possible since OSes differ too much.
