### ISSUE TITLE
Can't assign deleted IP address

### ISSUE THREAD

**Issue by darkbroodzed** [zerotier/ZeroTierOne#258]
In ZeroTier Central web interface
You can't assign any IP address to device if that IP was assign to any other device before.
How to reproduce.
1. create network
2. Add 2 device.
3. set IP 192.168.241.1 and 192.168.241.2
4 Delete second device from network.
5. Add third device and try set IP 192.168.241.2 for it. No error message or something, IP just don't save.

**Comment by adamierymenko** [comment]
This is a ZeroTier Central bug, so flagging as such... need a public bug repo page for that.

**Comment by bleppard** [comment]
This particular bug has been really maddening for me. I changed the IP address for a device and I want to change it back, but I am unable to.

**Comment by adamierymenko** [comment]
Fixed. Pushing live in a few minutes.

**Comment by adamierymenko** [comment]
The nature of the problem was this: deleting a member really just deauthorizes it and hides it in the UI. The IP wasn't removed, so it was still listed as used.

In the new code deleting a device removes its IP assignments as well as deauthorizing it and hiding it. So now when you delete devices you can reuse their IPs.

To fix old ones, re-add the old device and then delete it again. If you can't remember old device IDs e-mail contact@zerotier.com and give me your network ID and login and I can go in and manually clear them out.

**Comment by grtdeveloper** [comment]
@adamierymenko : i have sent you a mail regarding the recovery of my deleted addresses. Can you please help me out ? 

Thanks

**Comment by jerrychong25** [comment]
> 

Hi @adamierymenko ,

Sorry for bumping out old thread here.

I would like to deauthorize and delete a member via Zerotier localhost:9993 API as mentioned in https://docs.zerotier.com/self-hosting/network-controllers/.

Unfortunately, the API unable to remove assgined IP (In this case **10.1.1.200**).

DELETE Member API Details:
```
Request:
curl -X DELETE "http://localhost:9993/controller/network/XXXXXXXXXXXXXXXXX/member/aaaaaaaaa" -H "X-ZT1-AUTH: auth_token_here""

Response:
{}
```

GET Member API Details:
```
Request:
curl -X GET "http://localhost:9993/controller/network/XXXXXXXXXXXXXXXXX/member/aaaaaaaaa" -H "X-ZT1-AUTH: auth_token_here"

Response:
{
 "activeBridge": false,
 "address": "aaaaaaaaa",
 "authenticationExpiryTime": 0,
 "authorized": false,
 "capabilities": [],
 "creationTime": 1660278611038,
 "id": "563af8b3a5",
 "identity": "aaaaaaaaa:0:eacd8f65052054d842881f8bb530ea8e6750e262501783f2e8944ea16d4080684f25333dde47af796e27fac16bb8841494ecd164f5b0924b6beb1b0208699999",
 "ipAssignments": [
  "10.1.1.200"
 ],
 "lastAuthorizedCredential": null,
 "lastAuthorizedCredentialType": "api",
 "lastAuthorizedTime": 1660485003251,
 "lastDeauthorizedTime": 1661579147643,
 "noAutoAssignIps": false,
 "nwid": "XXXXXXXXXXXXXXXXX",
 "objtype": "member",
 "remoteTraceLevel": 0,
 "remoteTraceTarget": null,
 "revision": 8,
 "ssoExempt": false,
 "tags": [],
 "vMajor": 1,
 "vMinor": 10,
 "vProto": 12,
 "vRev": 1
}
```

After I've deleted a member, there is no way I could delete the assigned IP anymore.

Any solution to solve this issue via API only?

So that previously assigned IP could assign to new member ID.

Related:
- https://github.com/zerotier/ZeroTierOne/issues/859
- https://github.com/dec0dOS/zero-ui/discussions/109

Thanks.
