### ISSUE TITLE
Possible security breach

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#268]
I do not have node id 8056c2e21c in my authorised list, but somehow it has managed to join the network.

zerotier-cli listpeers | grep LEAF
200 listpeers 8056c2e21c 174.136.102.178/9994;183292;204043;active 258 1.1.0 LEAF

http://bgp.he.net/ip/174.136.102.178

Is this one of the network controllers managed by my.zerotier.com ?

**Comment by adamierymenko** [comment]
That's a network controller.

Peers may include hosts not on virtual networks. These may be network controllers, roots, etc. It's technically possible for any ZeroTier peer to send a packet to you as well, but if they're not in a virtual network that's just going to be ignored in the same way that an IPSec endpoint would ignore a packet with no recognized key or session.

A feature that's been requested for a while and will probably be added fairly soon is to display network IDs in the peer list. It's slightly harder than you'd think due to how ZeroTier's certs and networks work under the hood but it's quite do-able and would help us implement some other planned improvements to things like multicast.

**Comment by adamierymenko** [comment]
host 174.136.102.178
178.102.136.174.in-addr.arpa domain name pointer void.zerotier.com.

That's a gateway IP belonging to our main physical POP at CoreSite in Los Angeles.

**Comment by adamierymenko** [comment]
FYI:

ZeroTier actually has two tightly coupled layers. We call them VL1 and VL2. VL1 is the "virtual wire layer," a peer to peer network. That's what listpeers shows. VL2 is the virtual Ethernet layer, and implement wise is similar to VXLAN. Access to non-public VL2 networks is controlled by certificates. Any VL1 peer can talk to any other, but if it has no VL2 network cert it can't actually *do* anything. VL2 would simply drop anything it tried to send and would refuse to send anything to it.

**Comment by adamierymenko** [comment]
So you see a network controller in VL1 because even though it's not a member of your LAN you are talking to it -- it's the certificate and configuration authority for a virtual LAN you've joined.

**Comment by janjaapbos** [comment]
You can check whether an unknown node is a controller for one or more of the networks you have joined by execting the command: zerotier-cli listnetworks | grep 8056c2e21c

**Comment by adamierymenko** [comment]
There are two ZeroTier-hosted controllers right now: 8056c2e21c and e5cd7a9e1c. Unless the main POP in LAX is down they'll probably be coming from there... otherwise they will fail over and come from IPs assigned to OVH in Montreal (the secondary site).

**Comment by heri16** [comment]
Thanks for the splendid explanation Adam. Your awesome!
