### ISSUE TITLE
Display Private IP Information gathered by zerotier that will be Exchanged

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#270]
There is currently no way, via either GUI or CLI, to display which Private IP information would be exchanged. Is it all network interfaces or just one interface? How about multiple addresses on one interface?

On a side note, there is also no way to block or exclude certain private IP addresses from being exchanged or broadcasted to other peers. Some special private ip addresses like road-warrior VPN, and privacy VPN should remain private. Does that mean joining any earth zerotier public network would automatically allow other peers to see my privacy VPN and company VPN details? This is a security risk.  Being transparent about what information is gathered and broadcasted would be a good first step. Also to diagnose problems when direct connectivity fails or Private IP information is not exchanged properly.

**Comment by adamierymenko** [comment]
In 1.1.0 it is all interfaces. In 1.1.2 a filter has been added to exclude certain interfaces. The rules are OS-specific but on Linux and Mac interfaces beginning with 'tun', 'tap', or 'zt' are excluded. This is mainly to prevent recursion and the use of slower VPN links in preference to faster direct ones.

I'd prefer not to share IP info, but we went with this for two reasons. One is that such info really is not security critical and can be obtained in many other ways. How does knowing I'm 10.0.0.2 help an attacker? But more importantly, we added this feature because *there is no other reliable way to execute direct connections within the same local network*. Lots of local networks don't support multicast or are subdivided into many small broadcast domains with no multicast forwarding, so multicast announcements on the local LAN do not work reliably. NAT hairpinning (NAT traversal with yourself) is also unreliable and is slower in any case since the packets are now having to traverse your edge router twice. We were dragged into adding this feature because it is truly the only way.

Privacy VPNs are an interesting point I hadn't thought about, but that brings up a complex issue:

Let's say I have a privacy VPN engaged and all my Internet traffic is routed through it. In that case ZeroTier, being Internet traffic, is going to be routed through the privacy VPN, right? But ZT identifies me at least by device ID.

This is actually why privacy VPNs aren't very good privacy protection. Not only do you leak information via **any** background service that might be running (ZeroTier, any push notification system, etc.) but also via browser fingerprinting, OS/app fingerprinting, IP stack meta-data, etc. Privacy VPNs can prevent your ISP from tracking you or mangling your traffic and they can help you escape a national censorship firewall such as those found in China or Dubai, but beyond that they are not that great. Also important to note that they do *not* protect you much from a targeted attempt to identify you by a determined adversary. They're really only any good against blanket undirected surveillance and filtering.

Achieving strong privacy online actually requires some fairly stringent measures. The best you can do right now is to run Tor from inside a virtual machine with no persistent state -- e.g. a VM that boots from a volatile ISO image. Even better is to browse from a separate piece of hardware, but that is obviously really inconvenient. There are literally -- no exaggeration -- hundreds of ways to uniquely fingerprint a web browser. Modern browsers are massive beasts with large API surface areas that expose all kinds of information.

**Comment by adamierymenko** [comment]
My more security obsessed friends would say privacy VPNs are snake oil. :)

**Comment by adamierymenko** [comment]
Just FYI here is a nowhere near complete list of ways to fingerprint a browser:

 * Available system fonts and the *sort order* those fonts are returned in (which can say for example whether you freshly installed OS X 10.11 or upgraded from OS X 10.10 -- the fonts will sort differently!)
 * Loads and loads of timing side channels -- for example the time it takes to rapidly set and unset a cookie can leak information about what other cookies are in your cookie store via hash collisions and other timing artifacts.
 * Exact OpenGL behaviors via WebGL leak information about your video card and exact video drivers
 * CPU timing and concurrency measurements
 * Canvas drawing timings can also leak information about your video stack
 * Screen resolution, device resolution, display pixel resolution / retina sub-pixel modes, etc.
 * Your browser's security, caching, and local storage settings can constitute a unique fingerprint as there are so many of them and they differ machine to machine.
 * All browser extensions you have, their versions, and the sort order in which they appear in the extension enumeration.
 * Presence of any extensions such as special method/schema handlers
 * Often a page can determine whether you have recently visited another site by checking cache timings of loads of images and other resources on that site to see if they are fresh in your cache.
 * Mouse movement characteristics and resolution as the pointer crosses the web page
 * System clock and system clock resolution vs. popular NTP servers (in some cases if your OS picks NTP servers geographically this can actually leak rough location information via indirect clock skew measurement)
 * WebRTC provides a vector for easily determining your internal LAN IP address, TCP/IP stack information, etc.
 * Creative use of WebGL can be used to infer the presence and geometry of other windows or items on the desktop via timing side channels (saw a write-up on this once)
 * If you are running inside any kind of VM or hypervisor this can be determined with timings and other methods involving WebGL, etc.
 * Obviously anything like Flash or Java provides a *whole other VM* that can leak whole other categories of information. Flash in particular provides tons of surface area for exponentially more fingerprinting and side channel information leakage.

Ever wonder why so many popular media sites' pages are so large and slow? It's because they contain an extra couple megabytes of fingerprinting and tracking code that does all of the above and more. :)

All of that information can easily be gathered and taken together to form a fingerprint that uniquely identifies you with shockingly high accuracy even if you clear your browser every time or use private mode. Going behind a VPN or Tor with your regular browser and OS just causes you to leave a fingerprint trail that tells trackers you are now using a VPN or Tor (and who you are, and when you switched, etc.).

**Comment by heri16** [comment]
I have read the rationale of issue #180 . I completely agree private IP address do not really hurt security of user endpoints, but really hurt privacy and divulge info to network gathering operations for server endpoints. I don't need an attacker to know that the target server has an out-of-band interface that could be exploited.

For me, it is mainly to prevent recursion through ipsec interfaces, and also to troubleshoot paths through unknown/unexpected private IPs that are slowing down zerotier performance. For example, zeroconf ip addresses on Centos/RHEL is enabled by default but should never be used. Having a way to check the IP addresses sent out would be a godsend.

**Comment by adamierymenko** [comment]
In that case what we really want is to allow the user to override this in certain cases and specify which IPs should be sent, or should not, or turn it off entirely.

**Comment by adamierymenko** [comment]
Referencing the discussion at #273 and #272 -- I do think some expanded local config is on the table. I just want to think carefully about how it should work to preserve focus on user experience and simplicity.

**Comment by heri16** [comment]
Yes, please do take your time to design. It should be simple to start but easy to extend (e.g. plugins? or extensions like on google chrome store?). We need a guiding philosophy on this. Just like an easy-to-use macbook is great to many, but if Apple dropped the Terminal access, I think people like us would scream foul.

**Comment by adamierymenko** [comment]
Closing since recent anti-recursion improvements provide a hook for this, and because scope overlaps with other issues.
