### ISSUE TITLE
Faster dead path detection for improved resiliency when network conditions change

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#272]
See comments to #168 and other issues -- presently a dead path takes 60-120 seconds to fail over to a new one unless certain events such as a detected change in external IP trigger a reset. This should be improved.

**Comment by heri16** [comment]
And the other related problem that I saw is that zerotier never does failback after a failover of paths. Fallback to a previous path would be good if that path is now providing better latency.

BGP has something called "prepend as-path" so that the BGP routing algorithm can realize which path has a shorter distance.

**Comment by adamierymenko** [comment]
Failure to fall back *ever* may be a bug. It might be a bug that only manifests under certain conditions. We'll have to set up some test scenarios with multiple paths -- e.g. creating a couple tunnels between VPSes -- and the try killing paths and see what happens.

**Comment by adamierymenko** [comment]
We don't see this bug under "normal" use, but maybe it only manifests when there are multiple paths.

**Comment by adamierymenko** [comment]
Version 1.1.2 has been released -- it doesn't contain anything as ambitious or mesh-like as was discussed around here recently, but it does contain some path cleanup.

**Comment by adamierymenko** [comment]
Closed-- in 1.1.4.
