### ISSUE TITLE
Federated Root Servers / Local Relays

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#273]
Allow Network Controllers to proxy node traffic to Root Servers to facilitate VL1 connection setup.

This is useful under these conditions:
1. Internet route goes down between ZT Node and ROOT servers (because ISP is horrible at branch).
2. Internet route is still up between Network Controller and ROOT servers (because network controller has better ISP at datacenter).
3. ZT Node can still contact Network Controller via private IP address (because there is a direct/alternative path between them that is still up).

> Root servers faciliate connection setup and provisioning in VL1, while network controllers manage configuration and access control in VL2. The two systems are functionally separate. Root servers just help devices communicate, while network controllers are just regular devices that happen to be in charge of a few networks. But they are tightly coupled in the sense that VL2 is able to leverage VL1's cryptographic features to accomplish authentication.

**Comment by heri16** [comment]
Under current zerotier design, when the internet cuts out in a branch, devices in that branch are not able to find new peers via private IP paths (including peers that are in that same LAN subnet and peers that are in another building), which is sad for a mesh network.

Another way to do this is do use a Distributed Hash Table, instead of relying on just the network controller.

**Comment by adamierymenko** [comment]
Technically any node will already forward packets to any other node to which it has a direct connection. Federated roots is on the backlog (though not as a GitHub ticket).

ZeroTier isn't *quite* a mesh network, at least not yet. It's a peer to peer network. Its goal is rather ambitious: "SDN everywhere," and that involves doing several different things well. These are roughly:

 1. Provide stable connectivity between mobile and usually NATed endpoint devices. Do this with no special endpoint configuration and with very low latency even from cold start.

 2. Allow devices on the same local area network to find local paths to one another for better performance.

 3. Allow devices with multiple paths between one another to find the best path and/or use multiple paths concurrently (multipath), and automatically detect path failure in multipath scenarios and switch automatically.

The first versions of ZeroTier focused on (1), which means doing NAT traversal and led to the whole root server architecture to enable instant-on / low latency setup.

Later we experimented with multicast announcements to do (2) and found them unreliable for fundamental reasons, so we added PUSH_DIRECT_PATHS / #180 to do this reliably after deciding that the benefit was high and the security risk was minimal to nonexistent.

ZeroTier now does (1) and (2) very well.

(3) is a bit harder and will require a bit of additional intelligence. Right now ZeroTier is designed for typical endpoint situations where you have one LAN or WAN port (often with NAT to WAN), or maybe one WAN port and one LAN backplane port such as is often found on cloud VPSes such as Digital Ocean and Vultr. In that case you are going to one One Best Path at any given time, and once that path is found it is not likely to change unless you actually move your device to another network. ZeroTier currently copes well with stuff like "I close my laptop and walk to Starbucks."

But now we're throwing in situations where there are N paths between hosts of varying quality and where paths can fail silently without warning. Some paths should be used, some shouldn't, and they can drop or become unreliable, etc.

This is something we want to do but will take some thought. #272 is a big part of this, as is support for weighted multipath which currently does not exist.

I retitled this ticket and we'll call it the ticket for federated roots.

**Comment by adamierymenko** [comment]
We're talking about multiple topics here; just wanted to unpack a bit. Also I want to reference #168 since I'm starting to think that *some* enterprise deployments might really require that we suck it up and add support for hard-coding preferences. Sometimes only the IT / network eng really knows what paths should be preferred and the computer trying to do this itself is a case of software trying to be 'too smart'.

The reason we have an allergy to options like this is that I'm trying very hard to keep this project from catching enterprise disease and becoming bloated and hard to configure.

**Comment by adamierymenko** [comment]
Continuing on about #168 there is really no way ZeroTier can *reliably* tell the difference between a private IP that is part of an EC2 VPC network (and therefore free and fast) vs. one that tunnels over IpSec. I stress reliably-- latency measurements and such can *hint* at such a thing but latency can spike on LANs for various reasons and so false decisions are very likely here. This is a case where, say, blacklisting the IpSec tunnel IPs would make sense and might be the only way to force ZT not to use them.

**Comment by heri16** [comment]
Hi @adamierymenko Could you elaborate on what is meant by the below?
> Technically any node will already forward packets to any other node to which it has a direct connection.

I don't like enterprise bloat also. So I would recommend to go the simple route and prioritize paths based on latency and the consistency of that latency. Also to monitor all paths constantly to reprioritize every 10 minutes.

**Comment by adamierymenko** [comment]
The incoming packet path is:

 1. Is this packet (or fragment) for me?

 2. If YES, assemble and compute MAC using ECDH shared secret. If MAC fails, discard as corrupt or spoofed. If MAC succeeds, send to decode path.

 3. If NO, who is it for? If I have a direct path, increment the hop count (ZT hop count, not IP hop count) and forward. If not, forward it "upstream" which right now means a root server. The ZT hop count is a special field that can be modified by hops along a forwarding path-- it is the only part of the packet not MAC'd and simply serves to prevent forwarding races (a.k.a. the "software laser" effect). It's hard to have a forwarding race in ZT though since things go "up" in the hierarchy until they reach a root and then are discarded if there is nowhere else to go.

Note that there is no MAC or encryption or anything else in the forwarding step. Traffic is encrypted end to end -- the forwarder only knows the destination address.

This design allows two things:

 * It opens the doorway to mesh-like behaviors. When I designed ZT I designed it to be a semi-centralized P2P protocol with the capacity to evolve in a meshnet direction over time. My current thought is to keep the current "assisted p2p" paradigm but to mix in mesh-like behavior as a fall-back -- if the net is not reachable, you try to find peers via your existing peers. Meshnet fallback could get very interesting.

 * It means root servers can run exactly the same code as regular nodes (which they do). A root server is just a "blessed" peer with a big pipe and a stable IP address. There are currently two clusters of five nodes as described here: https://www.zerotier.com/blog/?p=577

 * It makes federated roots and designated relays easy.

It does introduce the potential that someone could flood you, though the effect would be no worse than an ICMP ECHO flood of an edge device. So far with this project I've focused on security hardening in this order.

 * Highest priority: making sure the code is robust against actual exploits -- see Buffer.hpp, etc. The code is very paranoid about validating incoming data at every stage of the decode path, even at the expense of a small amount of CPU time. (Bounds are checked religiously, etc.)

 * Right behind the highest priority is ensuring that an attacker can't worm their way onto a network they don't belong to.

 * Then, there's DOS attacks. DOS attacks are hard to defend against comprehensively, but there are mitigations. Current code takes a great deal of care to avoid anything that could be used for an *amplification attack*, which is the worst sort of DOS vector you can have. It also contains the beginnings of a proof-of-work based scheme for link triage under DOS conditions. But more is planned in this department for the future. I think it should be possible to make something that's actually *more* robust against DOS than a stock IP stack since we have so much more intelligence and crypto to leverage for things like proof of work triage, etc. But to really do this we're going to need to build test nets and game it out, and that's going to have to wait until we are a little bit larger. Making things just work more robustly is higher priority in most cases.

**Comment by heri16** [comment]
How do nodes know where to send packets in the type 3 case? Is there something that coordinates indirect path discovery? Are all nodes automatically relays?

**Comment by adamierymenko** [comment]
Right now there are two options: (1) I have a direct path to another peer, so send it directly, (2) send via root.

In the future there are likely to be more options such as mesh-like routing, local relays, etc., but that requires more local intelligence about paths.

**Comment by adamierymenko** [comment]
Discussion thread with proposal created in community:

https://www.zerotier.com/community/topic/86/root-server-federation-discussion-thread

**Comment by adamierymenko** [comment]
Basics of this are now in `dev`. Still wiring through. Will also involve #168
