### ISSUE TITLE
Actually implement ARP caching in netconf

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#275]
Any way to speed up ARP for IPv6 over zerotier while preventing ip spoofing?

**Comment by adamierymenko** [comment]
This is now done for IPv6 if you use the RFC4193 based addressing scheme. It emulates IPv6 NDP. It only does this for those addresses though so normal IPv6 addressing will be unchanged and will work normally.

**Comment by heri16** [comment]
The IPv6 implementation is very elegant. I know it might be bloat, but any chance this would be done for IPv4?

**Comment by adamierymenko** [comment]
Probably not. There's a fundamental problem with IPv4: there is not enough information in an address to make it automatic and stateless like IPv6, but too many addresses to distribute a dictionary to everyone. Thus IPv4 would involve some kind of dictionary to look up ARP.

The way ARP is implemented now is via a simple little hack that turns it into multicast keyed off the IP address, which... coincidentally makes it almost *exactly* the way it would be if we implemented ARP emulation and dictionary lookup. But the current approach has the advantage of more closely emulating what enterprise switches do (enterprise switches also often key ARP in this way to scale to large LANs), and more elegantly reproducing normal Ethernet behavior.

The IPv6 NDP emulation feature is *technically* a layering violation and would be rejected by many purists, but it's only used if you do addressing in one specific mode. Otherwise NDP functions normally via multicast. Its main purpose is to allow for a slimmed-down no-multicast build of ZeroTier in the future for small IoT devices.

**Comment by adamierymenko** [comment]
Multicast is actually pretty heavy, so leaving it out would result in a ZeroTier build that would be comparable in footprint to some of the micro IP stacks you see.

**Comment by heri16** [comment]
Would making static ARP entries work too? Concern that ARP problems within my zerotier network is affecting connectivity, and recent troubleshooting rounds proved that our concerns were true.

An easy to use GUI to freeze ARP records would help resolve issues for a significant amount of users having problems with multicastLimit 32 causing erratic bandwidth and ARP miss-rates due to recipient randomisation algorithm. Would also help reduce battery life on mobile devices significantly, and rule out a slew of connectivity issues (and corner cases), if the user could freeze the ARP cache like seen here: http://www.irongeek.com/i.php?page=security/arpfreeze-static-arp-poisoning
