### ISSUE TITLE
Security improvement: on Linux relinquish root and/or use seccomp extensions to sandbox process

### ISSUE THREAD

**Issue by adamierymenko** [zerotier/ZeroTierOne#312]
https://www.zerotier.com/community/topic/20/using-setcap-8-instead-of-running-as-root

**Comment by adamierymenko** [comment]
Closing for now since this conflicts with #317 -- once we relinquish root we can no longer trigger scripts like this.

May revisit later.

**Comment by adamierymenko** [comment]
Decided to close #317 instead since this is probably a better idea and #317 conflicts. #317 should be accomplished via other subsystems on Linux.

**Comment by kseistrup** [comment]
Any news here?

**Comment by adamierymenko** [comment]
The annoyance here is that setcap() applies to *files* not processes. We want the process to auto-relinquish regardless of what (fragile, easy to get borked) FS settings are in place.

One option would be for the process to setcap() its own binary and then fork() and re-exec itself in the event that it detects that it is not properly setcap()'d.

More research still needed.

**Comment by adamierymenko** [comment]
Just wanted to mention this too: https://hub.docker.com/r/zerotier/zerotier-containerized/

This is another way of running the service that uses cgroups and containers to isolate it. It's an option for people who want to avoid having this run as root on the metal.

**Comment by adamierymenko** [comment]
Actually seccomp may be the droid we are looking for:

https://outflux.net/teach-seccomp/

This way the process could start as root and then apply a fine-grained filter to itself that allows only what it needs without mucking around with filesystem ACL crap.

**Comment by zielmicha** [comment]
> The annoyance here is that setcap() applies to files not processes. We want the process to auto-relinquish regardless of what (fragile, easy to get borked) FS settings are in place.

It is possible to do `prctl(PR_SET_KEEPCAPS, 1); setuid(someuser_uid); prctl(PR_CAPBSET_DROP, ...)` to switch user (retaining all capabilities) and drop unneeded ones. Of course, `/var/lib/zerotier-one` would need to be owned by the new user.

**Comment by adamierymenko** [comment]
It could ensure that the files are owned by the right user immediately prior to changing UID. (An overarching goal here is to make the system robust and zero-config.)

Sounds interesting.

**Comment by zielmicha** [comment]
PR_SET_KEEPCAPS seems to be not enough - ZeroTier spawns /sbin/ip to manage configuration, and caps don't persist across execv (http://stackoverflow.com/questions/14636359). This also makes using seccomp nearly impossible (seccomp can't filter execv string arguments).

I'm going to make PR which:
- creates use zerotier-one if needed (e.g. doesn't exist yet)
- chowns /var/lib/zerotier-one if needed
- if supported (i.e. on Linux >=4.3), sets CAP_NET_ADMIN ambient capability and setuids to zerotier-one. Otherwise it stays root.

Will you likely merge PR with this functionality?

**Comment by adamierymenko** [comment]
You're welcome to give it a try. We'll merge it if it's clean and doesn't break things on systems where these things are not available. I'd suggest doing it against `dev` not `master` since that makes merging far easier. (Master is our tagged release branch.)

How hard would it be to implement what `/sbin/ip` does programmatically? I'm under the impression that it's actually kind of a PITA due to crufty kernel interfaces but I haven't looked too deeply.

**Comment by viraptor** [comment]
This is related to what I just started looking at. I made a dirty PoC that works and I'm happy to polish and submit it, but first, I'd like to confirm the design will be accepted.

I'm trying to add full seccomp support to zerotier-one which essentially splits the service into two parts. The lockdown starts right before the main `zt1Service->run()` loop and the next part allows only logging printout and relevant network operations. There is no disk IO interleaved anymore. All disk IO requests use an internal RPC to a new thread (seccomp profiles apply to threads separately) in a more abstracted way. Specifically things like:
```
OSUtils::readFile((_homeDir + ZT_PATH_SEPARATOR_S + "identity.secret").c_str(),id);
```
turn into
```
fileIo->getIdentitySecret(id);
```

The problem with "ip" is not that bad. There are two solutions:
1. Do the same thing as for file IO. Create another locked-down thread which gets only the (family, target, via) and has the rights to execute that right command.
2. Even though seccomp cannot filter on the content of the string, it can verify pointers, so you can do the following: reserve a page of memory, put all the known strings for the command in there, in seccomp verify each argument separately, apart from the variable ones. This means seccomp verifies you're calling:
```
execl(string_ip_command, read_only_family, string_route, read_only_op, variable_target, string_via, variable_via);
```
where 5 arguments can be verified and "route"/"via" keywords force interpretation of the remaining 2 arguments.
The page with those strings can be protected with `mprotect(..., PROT_READ)` and seccomp can prevent using `mprotect()` in the future.

In either case, the situation is the same for the following attack vectors:
- network exploit *cannot* execute files apart from know, pre-approved command and only has control over specific parameters
- network exploit *cannot easily* read/write arbitrary files - it would have to win a race with the file IO thread constructing the path in case where the path is constructed at runtime - for example writes to networks.d
- network exploit *can* mess with all other networks - they're handled in the same process
- local file parsing exploit *can* affect network since the parsing happens in the service thread, but *cannot easily* read/write arbitrary files (same situation as network exploit)

The separation of file IO could actually be a good idea anyway. If you wanted to move the service to some other storage system (unikernel zerotier appliance anyone?), all local IO is nicely separated into one place.

If this change is acceptable, I'll send a PR in a few days.

**Comment by adamierymenko** [comment]
Closing since this was implemented in a PR.
