### ISSUE TITLE
Strange Consul errors over a zerotier link

### ISSUE THREAD

**Issue by faddat** [zerotier/ZeroTierOne#314]
I'm just going to post the errors.  I really don't know what to make of this.  

![screenshot from 2016-03-09 01-19-33](https://cloud.githubusercontent.com/assets/7142025/13611435/26efa3fc-e595-11e5-9e9a-44e10312eaa6.png)

**Comment by adamierymenko** [comment]
This looks like something is blocking UDP over those links, which wouldn't be related to ZeroTier since it doesn't care about L3 packet types. I'd check iptables configuration of the host.

Also questions like this are good to post over here:

https://www.zerotier.com/community/

Unlike GitHub issues, which are better for bugs and such, the community remains online and searchable and becomes a kind of knowledge base.

**Comment by faddat** [comment]
Sure thing, and thanks!  I'll mvoe the discussion over there--- (or 
maybe, better stil, I"m giong to find that it just works now-- I've 
rebuilt the OS image for our cloudware.  )
