### ISSUE TITLE
Bridge Mode Traffic Always goes across ZT interface

### ISSUE THREAD

**Issue by dafyre** [zerotier/ZeroTierOne#321]
It would seem that when my ZT Interface is active and I am on the same LAN (and IP Range) that my ZT Is interface is on, my traffic ALWAYS passes across the ZT interface.

IE: If I ping a server on my LAN with the ZT service disabled, I get 1 or 2ms ping times (I am on WiFi).

When I enable ZT on my laptop, I get 75 or 80ms ping times (this is about the average for when I am off site).

Can someone confirm this?

**Comment by adamierymenko** [comment]
What's the interface (or route, depending on OS) metric for ZeroTier vs. WiFi?

We try to set a high metric on ZT interfaces so that if you belong to the same network via direct WiFi or wired Ethernet and ZeroTier your traffic will prefer the non-ZT route. But this relies on sane OS behavior and might not be consistent everywhere.

What's your OS?

**Comment by dafyre** [comment]
Hey Adam,

My OS is Windows 10, and under Network Connections -> Advanced -> Adapters
& Bindings, my ZT Interface is at the top of the list.
[image: Inline image 1]

My Interface Metric shows up as:

[image: Inline image 2]

10.130 is IP address of my wireless card.  10.103 is the ZT IP Address of
this laptop.

I have no wired connections hooked up to it.

**Comment by adamierymenko** [comment]
Don't see the images for some reason, but if the ZT interface is at the top that might suggest that it's the preferred route.

**Comment by dafyre** [comment]
The links in the post above work now.  I will tinker some tonight and see if that fixes the problems or not.
