### ISSUE TITLE
Random UPnP Ports

### ISSUE THREAD

**Issue by heri16** [zerotier/ZeroTierOne#365]
Running Zerotier 1.1.14 and the UPnP port on Windows is 30186, instead of 49994.
This is not good as firewall whitelist will no longer work.

**Comment by adamierymenko** [comment]
This is a feature. It now picks a random port per machine. The port is stable because it's computed from the identity/address.

This was done because a good percentage of routers out there can't handle more than one uPnP mapping behind them from the same port. The mapping stops working. In a few cases it actually crashes the router.

**Comment by adamierymenko** [comment]
Since 1.1.6 it also pics a *third* port and uses it if 9993 doesn't work. That's because some routers can't handle more than one device doing UDP hole punching with the same internal port. Mappings stop working or random hosts get random packets designated for each other.

**Comment by heri16** [comment]
Wow. That explains why it is broken now on my environment, with
intermittent connectivity. Is there a way to downgrade to 1.1.4 on Windows?
Or Is there a way to reverse this behavior during installation or via
command line?

**Comment by janjaapbos** [comment]
Perhaps you can update your whitelist to allow port 49994, as Adam explained this is a stable value based on the identity. For each zerotier node (identity) their will be a different value computed, so if you have more than one zerotier behind your firewall, these ports should also be included.

**Comment by heri16** [comment]
That's too many changes for IT operations, considering that mangling,
connection marks, Quality of Service queues, and filter rules all depend on
static ports, setting one each for every node will be messy and error
prone. Unless there is an L7 filter that could be provided, zerotier will
remained blocked in an enterprise environment where the firewall
"security" is someone's job description and responsibility. Is the an L7
rule you could provide?

**Comment by janjaapbos** [comment]
@heri16 that's a great suggestion. I am sure that we should be able to describe a L7 pattern for ZeroTier like here: https://github.com/l7-filter/layer7-patterns

**Comment by adamierymenko** [comment]
Hmm... that might be difficult since ZeroTier packets are encrypted. The packet format can be seen [in Packet.hpp](https://github.com/zerotier/ZeroTierOne/blob/master/node/Packet.hpp#L349) and is relatively simple, but there is not much that is consistent across packet exchanges except source/dest address. Creating L7 rules for each ZT source/dest address would be as hard as whitelisting every UDP port. The same problem exists for other encrypted protocols like IPSec, OpenVPN/UDP, etc.

Does your edge router have a "port triggering" or stateful firewall feature? If clients are allowed to initiate bidirectional UDP "conversations," that will work.

It would in theory be possible to implement a L7 filter/NAT-ALG for ZeroTier but this would require more than a simple matching rule. It would require code to track source/dest ZeroTier addresses and possibly validate them against the ZT network itself.

**Comment by adamierymenko** [comment]
We could perhaps introduce a local setting here. We've been reluctant so far but I think we're at the point where things are stable enough that local settings can be introduced without leading to feature bloat.

But yeah, the problem is that there are so many broken consumer routers that workarounds like this are needed as 'default' settings.

**Comment by heri16** [comment]
If port triggering is used, what would the rule look like?

**Comment by adamierymenko** [comment]
Hey, just looking through GitHub and saw this question again.

What the rule would look like would depend on your router/firewall, since different ones have different rules engines.

What's wrong with normal stateful firewall behavior for outbound UDP?

Also keep in mind that while alternate ports are now used, they do not have to be open. ZeroTier will still work even if only 9993 is reachable or can reach the outside world. So you could just block everything but 9993 and it should continue to work.
