### ISSUE TITLE
Make compression switchable on a per-network basis (was: is ZT vulnerable to CRIME-type attacks? probably not but related question.)

### ISSUE THREAD

**Issue by zielmicha** [zerotier/ZeroTierOne#391]
From cursory glance at the ZeroTier code, it seems that it compresses every packet with LZ4. Compressing data before encryption makes [CRIME](https://en.wikipedia.org/wiki/CRIME)-like attacks possible. 

I would recommend turning off compression. (there are alternatives, like using my [SafeDeflate](https://users.atomshare.net/~zlmch/compress.pdf), but it's still not polished enough).

**Comment by adamierymenko** [comment]
Thanks for taking a look! Security feedback is always welcome.

I've considered making this a switchable option per-network, and also for performance reasons. Might do this in the current rev since it's easy.

Whether or not this is an actual risk depends very much on the details of deployment. Every major novel exploit seems to result in a take-away rule, and for CRIME that was "never compress something secret together with something attacker-influenced."

`[CRIME] relies on the attacker being able to observe the size of the ciphertext sent by the browser while at the same time inducing the browser to make multiple carefully crafted web connections to the target site. The attacker then observes the change in size of the compressed request payload, which contains both the secret cookie that is sent by the browser only to the target site, and variable content created by the attacker, as the variable content is altered. When the size of the compressed content is reduced, it can be inferred that it is probable that some part of the injected content matches some part of the source, which includes the secret content that the attacker desires to discover.`

So for someone to use ZT's compression to their advantage, they would have to be able to induce members of a network to send chosen plaintext. They would also have to have some clue about the nature of the secret they are trying to obtain.

A plausible real world scenario would be something like this:

A deployment is using a virtual network as a backplane for a web app. It carries traffic from front-end proxies *as well as* traffic to/from backend database servers. The latter includes queries that contain user authentication tokens.

An attacker could in theory send crafted plaintext via the web front-end and perhaps, with some knowledge of the nature of backend comm (e.g. what database they are using) and a lot of patience, obtain information about user authentication cookies.

It's not a trivial wham-bam attack but it's feasible for a highly skilled attacker. AFIAK it would be *harder* in the ZT case than with CRIME because the ZT network can carry lots of traffic all mixed together. The attacker would have to employ a lot of heuristics to discern packets of interest, etc.

So yeah -- we can make this a toggle-able per-network option and perhaps explain in the docs that compression can improve performance for some use cases (e.g. uncompressed filesystem traffic) but can also introduce a potential attack vector.

**Comment by adamierymenko** [comment]
Actually on second thought I'm not sure if CRIME is very feasible here. (Though we still might make this toggle-able.)

Problem is that ZT does not mingle packets. If the attacker can inject chosen plaintext into traffic that gets relayed over the virtual network via HTTP, those are completely separate from other packets that might carry e.g. database auth tokens. Compression is per-packet, not streaming. So this would give an attacker no information.

It's all coming back to me now-- I actually did consider this long ago and concluded that CRIME type attacks are not very feasible in a design like this.

But we'll probably make it switchable for performance reasons also.

**Comment by adamierymenko** [comment]
BTW SafeDeflate looks like really interesting work! Reading paper now. :smile:
