### ISSUE TITLE
CLI should be able to examine system ARP/NDP tables and reverse MAC->ZT to get real Internet IP of a virtual IP

### ISSUE THREAD

**Issue by rebroad** [zerotier/ZeroTierOne#392]
Sorry if github issues is not the correct place to request features (although bugs/features/fixs are subjective, IMHO, so all the same thing).

Raising this issue to see if this would be a desired feature - I am already pretty sure I'd know how to code it so could go straight ahead and add this feature, but if someone else is already working on it, then I'll not do so.

**Comment by adamierymenko** [comment]
ZT emulates an Ethernet switch and other than the new rules engine does virtually nothing to inspect IP or other traffic that it carries. Implementing this in the core would require something to scan traffic, pick out source IPs, and track them, which would add memory and overhead. We generally like to avoid adding overhead for any non-essential reason in order to keep the core as small and simple as possible.

But an alternative method could be done in the CLI only without using the core by looking at the system ARP table, picking out the MAC, reversing it to get the ZeroTier device ID, and then grabbing that peer record from the service and displaying the route. This is probably the best approach. I've added it to the backlog.

**Comment by rebroad** [comment]
@adamierymenko I already wrote a little script that does a listpeers every few seconds, and shows the differences from the last one. Then when I ping a ZT IP address I see it pop up on the output, showing the internet IP address and the ZT public fingerprint.

I could see that earth.zerotier.net was the same IP as www.zerotier.com for example, and a HTTP GET for "earth.zerotier.net/" to the IP address of www.zerotier.com confirmed this, and confused the script obviously that displays the ZT earth IP address :)

Anyway, all that might be required would be the ability to log to a file as new peers are added (or go active) and this could be consulted by the program that needs to make the correlation. A bit messy though. an API or RPC call would be better. In terms of overhead, I'd have thought it would be no more than what is used to produce the listpeers output.

**Comment by adamierymenko** [comment]
Closing since this feels a bit out of scope. Triage.
