### ISSUE TITLE
[RFC] Make TCP relay address configurable

### ISSUE THREAD

**Issue by zielmicha** [zerotier/ZeroTierOne#403]
In many networks, only TCP ports 80 and 443 are allowed. I guess that the global tcp relays are not guaranteed to be fast. It would be nice to be able run TCP relay yourself and configure ZeroTier to use it.

I can see that this configurability might be against zero-conf goals of ZT, but if these changes are acceptable, I'm going to implement them and make PR.

**Comment by adamierymenko** [comment]
We're going to punt this one because that whole thing is going to die soon.

We're planning on introducing HTTP (and/or web sockets, have not decided) as a first-class core transport alongside UDP. This would be a fallback-- UDP is better for encapsulating a packetized protocol for obvious reasons. But it would have two advantages: allowing ZT to run in web-proxy-only corporate net environments, and allowing ZT to run **in a browser**.

The latter is a big secret so shhh.  😄
