### ISSUE TITLE
Feature request - add listpeers to gui

### ISSUE THREAD

**Issue by Tinytimrob** [zerotier/ZeroTierOne#433]
I am trying to migrate from Hamachi to ZeroTier.

One of the features of Hamachi is to list all of the users in the network along with their assigned IP addresses (IPv4 and IPv6). You can also see the state of the tunnel to each of the users. And you can right click them in order to ping them.

Right now there isn't any way to know who is in the network or what the IP address is of each user in the network without having access to MyZeroTier (at least not from what I can see). So I will have to give out a list of the users and IPs by hand. This is very clunky :/

It would be great if you could consider this sort of feature for the ZeroTier One GUI.

**Comment by Tinytimrob** [comment]
This was blocking our migration so I wrote a temporary gui for this in the meantime if anyone is interested.
https://bitbucket.org/Ginever/ragnatela

**Comment by adamierymenko** [comment]
We used to have this but took it out because users found it confusing and alarming. "Does this mean all these people are on my computer right now?" No, etc. You also can see infrastructure and controller nodes in there. The presence of a device in that list does not indicate that it's talking or able to talk on any of your networks.

I think if we re-add it we should implement showing of network memberships with devices and try to come up with a clearer UI.

**Comment by adamierymenko** [comment]
Basically listpeers is a very low-level view of the p2p network and doesn't indicate permissions or access.
