### ISSUE TITLE
ZT only using wireless interface

### ISSUE THREAD

**Issue by ndrego** [zerotier/ZeroTierOne#436]
I am using ZT on OS X and have the following problem: when connecting to devices on a local network via ZT IP addresses, it will only work when I'm connected to WiFi. If I'm connected to the same network via ethernet, ZT will not work, no matter how long I wait. Furthermore, if I have both ethernet and WiFi on and connected to the same local network (ZT is functional at this point) and then turn WiFi off, it will cease to work, even with numerous ZT restarts.

It's as if it's only bound to the WiFi interface and won't detect interface changes. FWIW, this has been a problem for a long while but I only just figured out that it's related turning to WiFi on/off.

The even stranger part is that it will see the other ZT peers on the local network if I do `listpeers` but it refuses to connect to them.

I am running version 1.1.14 on all clients.

**Comment by glimberg** [comment]
This sounds as if it could be a configuration issue on your wired network vs your wireless network.  It's as if your wired router is blocking ZeroTier packets to different nodes and/or the ZeroTier root servers, but the wireless network is not.

**Comment by ndrego** [comment]
Well, we're talking about an internal/local network on my end, with all devices on that same network. In the wired case it's going through a switch (no router) and in the wireless case, it's going through a wireless AP (wireless router configured to be in pure AP mode). Both of those are directly wired to an Ubiquity EdgeRouter.

**Comment by janjaapbos** [comment]
Do you also experience the problem when you have wifi off completely (reboot Mac with wifi disabled). It likely is related to having the same network scope for wifi and wired. This could affect OSX firewalling.

**Comment by ndrego** [comment]
Yes, doesn't matter if it's freshly rebooted or the WiFi is turned off
after some time.

**Comment by glimberg** [comment]
Is there any configuration difference in your router for the port the wired network is plugged into vs the port the wireless AP is plugged into?  Can you send us your `ifconfig` output.  Either on here, or via email to support@zerotier.com.

By design, ZeroTier uses any and all available network interfaces and choses the best one for connectivity between clients and normally uses whichever interface the OS prefers.  It doesn't discriminate between wired, wireless, tunnels, etc.  For instance, I have WiFi calling enabled in FaceTime on my Mac.  I've had instances where ZeroTier communicates to other nodes via the ipsec tunnel that the OS creates for WiFi calling (because while not configured to be routable by default in the OS, for some reason T-Mobile will route packets to the general internet sent through that tunnel).

**Comment by ndrego** [comment]
Sorry - forgot that both go into another switch before hitting the router, so no difference in configuration. I will send `ifconfig` output via email. Should it be with WiFi enabled or disabled? Or both?

**Comment by glimberg** [comment]
Both

**Comment by ndrego** [comment]
Sent

**Comment by lixpng** [comment]
@ndrego Hi, have you solve this, I meet same problem too.
