### ISSUE TITLE
Can zerotier only use p2p link?

### ISSUE THREAD

**Issue by nkcfc** [zerotier/ZeroTierOne#532]
In my campus  network  I  will be charged by ￥4/G  if I  transfer data to other network. So I want zerotier never use your network  beside some  necessary communication data to find a path to connect them.   My  clients  are all in my  campus network but they don't have static ip , so I  want to use zerotier.

**Comment by janjaapbos** [comment]
Best way to check this is to try and verify listpeers. The peers should be listed with their campus ip number if that is used. The zerotier instances will connect through the best link available. Further you can create a moon on the campus network and have the client configured to use that instead of the public root servers.

**Comment by nkcfc** [comment]
Thank you. By the way, can I disable public root servers for some clients ?

**Comment by adamierymenko** [comment]
You can't disable right now without editing code, but you can do this:

https://www.zerotier.com/manual.shtml#4_4
