### ISSUE TITLE
How to Change the Default Port?

### ISSUE THREAD

**Issue by adit-s** [zerotier/ZeroTierOne#640]
Hello. This is probably a basic question, but I just started using ZeroTier and haven't been able to figure out how to change the default port from 9993 to a different value. 
Going through the docs and info I can find, I understand that I need to include/update the local.conf file. Is that correct and can someone tell me where it should be located for Mac?

Based on the docs, I think it should be in /Library/Application Support/ZeroTier/One for Macs. There isn't one there by default, so I created it with the following content, but it didn't seem to make a difference when I use the ZeroTier Mac App and not the cli.
Content of local.conf file:
 {
        "settings": {
                "primaryPort": "####"
        }
}
OR
{
        "settings": {
                "primaryPort": ####
        }
}

I hope someone who's already done this can share their experience and give me a hand.

Thanks in advance,
Adit Sood

===
PS If the JSON API file for the Mac App uses a different procedure, please let me know how to adjust it. [The contents of http://127.0.0.1:9993/ are simply {} so it doesn't seem to pick up the value from the local.conf change]

**Comment by joseph-henry** [comment]
First question,

`/Library/Application Support/ZeroTier/One/local.conf` is the correct file, yes. The following works for me:

```
{
        "settings":
        {
                "primaryPort": 9994
        }
}
``` 

Then restart your client with: 

`sudo launchctl unload /Library/LaunchDaemons/com.zerotier.one.plist`
`sudo launchctl load /Library/LaunchDaemons/com.zerotier.one.plist`

To verify this succeeded, check the contents of `/Library/Application Support/ZeroTier/One/local.conf`. In our case it should now contain `9994`.
***

Second question, 

In order to use that API, you need to provide it the auth token. This can be done like so:

`curl -v http://localhost:9994?auth=$(sudo cat /Library/Application\ Support/ZeroTier/One/authtoken.secret)`

And for instance, to view the status of your node, use:

`curl -v http://localhost:9994/status?auth=$(sudo cat /Library/Application\ Support/ZeroTier/One/authtoken.secret)`

Let me know if you have any further questions.
