### ISSUE TITLE
DEV - Controller Doesn't Report Network Created

### ISSUE THREAD

**Issue by ChanceM** [zerotier/ZeroTierOne#680]
I'm trying to build a package for ZeroTier on pfSense.
I build the latest dev branch. Post network to controller. No output. Get `/controller/network`, response = [].
ls of `/var/db/zerotier-one/controller.d/networks` shows .json file.

**Comment by glimberg** [comment]
Tracked this down to this line:

https://github.com/zerotier/ZeroTierOne/blob/f9b07c63db322b1ce0b95ef2844dccb7b9554eea/controller/DB.cpp#L342

Looks like a bug in FileDB due to fixing some performance issues with RethinkDB.  When using FileDB, a newly created `network` JSON object doesn't have a sub object named `config`, while new networks created in RethinkDB do.  This results in the network never being added into an internal map when using the default FileDB mode.

**Comment by pkpowell** [comment]
With the latest dev, `Get /controller/network/<nwid>/member` is returning some wonky json (weird double double-quotes) `{""memberid":1}`

`Get /controller/network`and `Get /controller/network/<nwid>` look fine.

**Comment by glimberg** [comment]
Fixed in dev:  https://github.com/zerotier/ZeroTierOne/commit/57b96af2c41ed63a12bfb41044f242fc55ab1358
