### ISSUE TITLE
Build with gcc-4.8

### ISSUE THREAD

**Issue by dtoubelis** [zerotier/ZeroTierOne#697]
We are including zerotier client with our embedded devices and our toolchain (yocto/morty) uses gcc-4.8. The code compiles (v1.2.4) but I see some warnings when it is executed. Replacing toolchain is not an option, so I have couple of questions:

- What is the reason for gcc-4.9+
- Is there any (older) version compatible with gcc-4.8 that we could use
- And is there a way to make the code compatible with gcc-4.8

Thanks

**Comment by joseph-henry** [comment]
The requirement is mainly due to our usage of a particular JSON library. We will potentially replace this in the future if it continues to be an issue. It's possible you could go back to 0ad6b4105a50bc081ac1c8bd4e4ffe656b8f0b26 but that's pretty old (Jun 22, 2016). You'd be giving up many of the modern ZeroTier features such as the performance/reliability upgrades, rules engine, tagging, etc.

The library in question: https://github.com/zerotier/ZeroTierOne/tree/master/ext/json

Edit: May I ask what your exact target is?

**Comment by dtoubelis** [comment]
That must be a very good library that you willing to sacrifice compatibility :-) From my experience nothing comes close to jansson in terms of API and code quality in plain C world (http://www.digip.org/jansson/) ;-)

Our current build is for x86_64 (intel-corei7-64 to be absolutely precise) and we are working on ARM7, ARM64 and i386 versions shortly.

**Comment by adamierymenko** [comment]
We've introduce some other C++11 code elsewhere too. So far we are keeping it out of the core but we are using it in the controller and the service code.

C++11 is pretty stable now. At some point you have to stop supporting old stuff.

We have qemu-chroot environments with Alpine Linux that allow static binaries to be built. We do this to provide binaries for very old or non-standard Linux distributions. I can post these chroot trees somewhere if you'd like.

**Comment by dtoubelis** [comment]
Yes, if you can point me to the static binaries environment that would be awesome.
