### ISSUE TITLE
How to orbit moon on android and ios devices?

### ISSUE THREAD

**Issue by erguotou520** [zerotier/ZeroTierOne#716]
Thanks for your great softwares.

**Comment by adamierymenko** [comment]
This is not currently exposed.

We are going to simplify this whole thing, including getting rid of the confusing over-wrought terminology. Just wait for 1.4. :)

**Comment by erguotou520** [comment]
ok thanks

**Comment by lifehome** [comment]
So when would be version 1.4? I think this feature is crucial as air-gapped mobile devices cannot connect due to disconnected to `planet`.

**Comment by justyns** [comment]
Is there any additional information on what this will look like in the future?    I couldn't find anything about 1.3 or 1.4, so I'm assuming it's not going to be "soon"?

**Comment by fatalitylive** [comment]
Looking forward to the release of 1.4

**Comment by wanjochan** [comment]
> So when would be version 1.4? I think this feature is crucial as air-gapped mobile devices cannot connect due to disconnected to `planet`.

Hunger for the new version that support iOS/Android to orbit moon without planet, i.e. the off-grid mode.
 
Here is our case, a private science park that have multi buildings, which they are limited to the internet, so we want to deploy the moon in every building so that all leaf can communicate within the park only without internet and "planet"....
