### ISSUE TITLE
Feature: Multiple ports?

### ISSUE THREAD

**Issue by dragon2611** [zerotier/ZeroTierOne#777]
It looks like you can set an IP/Port in the config but is it possible to specify additional IP's/Ports for zerotier to bind to?

I see a primary port in local.conf but not a Secondary Port.

I'd like to bind to TCP/443 on the machine that hosts the gateway for one of my networks but as a secondary to be used if udp 9993 is blocked form the hotspot my Laptop happens to be using.

I'd then want to add that particular zerotier ID with the ports UDP/9993 and TCP/443 in the virtual section of the client so that in theory if the hotspot was blocking zerotier it's more like to be able to get a connection.

**Comment by glimberg** [comment]
The TCP/443 proxy is not something that's baked into ZeroTier itself (other than sending data to the running proxies).  That's actually a separate process and service that we run for users in extreme situations where UDP connectivity cannot be established.  It's also something that's not user configurable.  You'd have to run your own `tcp-proxy` service and recompile the ZeroTier clients yourself to point to yours instead of ours.  Additionally, it's also not used by the Android or iOS clients at all.

It looks like it was removed from the source tree sometime between 1.2.4 and 1.2.6 as we're deprecating it for something better in the future, but it's not done yet.  We have several machines around the world running the TCP proxy service in an ANYCAST block so that the nearest one will be used.  The source for the version currently running can be found here:  https://github.com/zerotier/ZeroTierOne/tree/1.2.4/tcp-proxy.  It makes things look like a TLS connection to a web server and acts as a remote UDP port for a node.

As for UDP, there are already 3 ports opened for use by default.  One is the default of UDP/9993 configurable via `local.conf` as you noted.  A second derived from the node ID, and a 3rd for easier use with uPnP/NAT-PMP mappings.
