### ISSUE TITLE
Cannot connect to ZeroTier service (VPNs and Hypervisors again)

### ISSUE THREAD

**Issue by darkain** [zerotier/ZeroTierOne#799]
Possibly related to https://github.com/zerotier/ZeroTierOne/issues/357 and/or https://github.com/zerotier/ZeroTierOne/issues/308

ZeroTier One: 1.2.8
Windows 10: build 1803
VPN service: Viscosity
Hypervisor: VMWare Workstation

It seems like the previous testing and fixing revolved around OpenVPN and Hyper-V. In my particular setup, I'm running Viscosity (which honestly shouldn't be installed anymore since I'm using ZeroTier One as a replacement now), and VMWare Workstation. I'm getting the dreaded "Cannot connect to ZeroTier service" when trying to add a network. I did this because the network list window showed I wasn't connected to anything. I then went to my local network connections to discover the ZeroTier connection was already registered, however it is marked as "unplugged." I tried this with both my wired and wireless NICs in both combinations of connected/disconnected to see if ZeroTier used cable state replication (something VMWare optionally does), but that didn't change anything.

Testing steps:

Rebooting:
no change

Uninstall Viscosity and reboot:
everything is working as expected now.

It appears as though ZeroTier is still conflicting with other VPN providers (possibly mixed with other Hypervisors?) 

![zerotier](https://user-images.githubusercontent.com/2524251/41986184-3a3574dc-79ea-11e8-8149-276b5914d78a.png)

**Comment by glimberg** [comment]
This is likely due to the issue fixed here in the `dev` branch: https://github.com/zerotier/ZeroTierOne/commit/352ec3430f50da47132e741c4bb19ca194e324f6

Basically, by default in the WinSock library, the FD_SETSIZE define defaults to the obscenely low value of 64.  This influences the maximum number of network sockets a program can use at once.  To contrast, this is set by default to 1024 on Linux.  Well we used that macro to define the maximum number of sockets ZeroTier will listen on.

ZeroTier opens up a TCP and UDP socket on each IP address assigned to each network adapter.  When you start adding Virtualization adapters such as VMWare, Other VPNs, that number of sockets increases.  Throw in a Dual Stack IPv4/IPv6 network and... Well with temporary IPv6 addresses, I'm sure you can see how this gets over 64 quite quickly.  ZeroTier then gets into a state where it can't open all of the listening sockets it needs, and you get the `Can't connect to ZeroTier Service` error.

In the change listed above, FD_SETSIZE is increased to 1024.  This will be in the next release.

**Comment by gMan1990** [comment]
can use proxy to ZeroTier Service?

**Comment by parthghughri** [comment]
> 
> 
> This is likely due to the issue fixed here in the `dev` branch: [352ec34](https://github.com/zerotier/ZeroTierOne/commit/352ec3430f50da47132e741c4bb19ca194e324f6)
> 
> Basically, by default in the WinSock library, the FD_SETSIZE define defaults to the obscenely low value of 64. This influences the maximum number of network sockets a program can use at once. To contrast, this is set by default to 1024 on Linux. Well we used that macro to define the maximum number of sockets ZeroTier will listen on.
> 
> ZeroTier opens up a TCP and UDP socket on each IP address assigned to each network adapter. When you start adding Virtualization adapters such as VMWare, Other VPNs, that number of sockets increases. Throw in a Dual Stack IPv4/IPv6 network and... Well with temporary IPv6 addresses, I'm sure you can see how this gets over 64 quite quickly. ZeroTier then gets into a state where it can't open all of the listening sockets it needs, and you get the `Can't connect to ZeroTier Service` error.
> 
> In the change listed above, FD_SETSIZE is increased to 1024. This will be in the next release.

Can You Explain How to do that? I go through that thread that you've mentioned but can understand how to increase that limit.
