### ISSUE TITLE
Cannot use system proxy configuration for TCP/443 in linux

### ISSUE THREAD

**Issue by jothoma1** [zerotier/ZeroTierOne#801]
Hi,
I'm trying to use zerotier on my company network. UDP/9993 is blocked. 
TCP/80 & TCP/443 must pass by a proxy squid configured on the system.

On my CentOS machine, i try 2 things for configuring our proxy:
1.  /etc/profile 
2.  add zerotier-one user a bash and add .bash_profile wich export http_proxy and https_proxy.

Clearly zerotier dont use the proxy defined. My firewall logs show that it try to connect directly on 443.
Join command show ok but the node is always offline and dont appear on my.zerotier.com interface.

I know it's not the best way, as i normally have to open UDP/9993 (or other defined in local.conf) but in some situations it would be great to use system-wide proxy's settings

How can we do this ? Can you add a proxy option in local.conf ?

**Comment by adamierymenko** [comment]
I'll let you in on a little secret... well not really a secret because it's documented in the code but...

It's not actually using HTTPS. The existing TCP tunnel system is making its traffic look like HTTPS.

This code as it stands is slated for replacement. We're planning to replace it with native TCP between peers instead of the current ZeroTier-dependent tunnel hack. As it stands the existing hack is considered a last resort connectivity option. It's very slow and is there only to provide limited connectivity in cases where e.g. you're behind super-restrictive public access points. If you are using ZT in production you need to allow its UDP traffic and allow P2P. You'll get much, much better performance.

**Comment by capqwerty** [comment]
Thanks for the update have similar issues as jothoma1. In my case, other https traffic works via a transparent firewall/proxy, Unfortunately ZT did not.  Is there any thought gone into what the replacement is going to look like and what it will be able to handle?
