### ISSUE TITLE
[Request] Fedora packaging for armv7hl

### ISSUE THREAD

**Issue by leleobhz** [zerotier/ZeroTierOne#826]
Hello,

Since Fedora now supports armv6hl and aarch64 for raspberry pi officially, its possible to package the armv7hl version too?

```
[root@minigate ~]# uname -a 
Linux minigate 4.17.12-200.fc28.armv7hl #1 SMP Fri Aug 3 16:09:35 UTC 2018 armv7l armv7l armv7l GNU/Linux
[root@minigate ~]# dnf install zerotier
Última verificação de data de vencimento de metadados: 0:06:46 atrás em ter 14 ago 2018 10:07:56 -03.
Nenhuma correspondência para argumento: zerotier
Erro: Não foi possível encontrar uma correspondência
[root@minigate ~]# cat /etc/yum.repos.d/zerotier.repo 
[zerotier]
name=ZeroTier, Inc. RPM Release Repository
baseurl=http://download.zerotier.com/redhat/fc/$releasever/
enabled=1
gpgcheck=1
[root@minigate ~]# 
```

Thanks

**Comment by theyosh** [comment]
Hi,

I compiled it manually on a armv7hl device from the git code. By default it will not compile due to unknown architecture. But I made just a lame change in the make file `make-linux.mk`:

Look where all the other arm version checks are and add the lines below.

```
ifeq ($(CC_MACH),armv7hl)
        ZT_ARCHITECTURE=3
        override DEFS+=-DZT_NO_TYPE_PUNNING
        ZT_USE_ARM32_NEON_ASM_CRYPTO=1
endif
ifeq ($(CC_MACH),armv7hl)
        ZT_ARCHITECTURE=3
        override DEFS+=-DZT_NO_TYPE_PUNNING
        ZT_USE_ARM32_NEON_ASM_SALSA2012=1
endif
```

And run `make`. This worked for me I guess, as I am able to start the daemon and I see it in my admin panel at ZeroTier.

So now my Xperia X mobile phone running Jolla OS is connected to ZeroTier.  :)

**Comment by adamierymenko** [comment]
Fixed in `dev`

**Comment by theyosh** [comment]
Hi,

I am sorry to say that I turns out that this is/was not working for me. Compiling went ok, but running the daemon resulted in segmentation fault. So I should maybe tested it a bit more before suggesting this change.

So, I did, and here is the full info that I can give now.

Software is compiled on: armv7hl-meego-linux-gnueabi (gcc -dumpmachine)
OS: Sailfish OS 3.0.3.10 (Hossa) (Mobile phone)
So I changed the ZT_ARCHITECTURE now from 3 to 4, and I am able to compile and run the daemon on the background.

So, I am not sure how to make sure that the value 4 is the right value. As I am only testing it now on my mobile phone.Also I do not know if the initial person in this issue has it working.....

For me, I need the value of 4 to get the software running. I am planning to make rpm packages for Sailfish OS.
