### ISSUE TITLE
ZeroTier Unsigned Driver?

### ISSUE THREAD

**Issue by ecapuano** [zerotier/ZeroTierOne#851]
**Is your feature request related to a problem? Please describe.**
Unsigned drivers can be problematic for security.

**Describe the solution you'd like**
I could be mistaken here as I am trusting the output of a single tool (osquery), but it seems the ZeroTier tap driver may be unsigned? Specifically, `C:\WINDOWS\system32\drivers\zttap300.sys` If this is accurate, it would be ideal to see a signed driver. 

**Additional context**
When performing an "loaded driver" query via osquery, the results show the ZeroTier TAP driver as being unsigned. Full disclosure, I have not validated this any further than what osquery responded with.

```
"host_hostname","class","date","description","device_id","device_name","driver_key","image","inf","manufacturer","provider","service","service_key","signed","version"
"<redacted>","NET","1439424000","ZeroTier One Virtual Port","ROOT\\NET\\0000","ZeroTier One Virtual Port","HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Class\\{4d36e972-e325-11ce-bfc1-08002be10318}\\0002","C:\\WINDOWS\\system32\\drivers\\zttap300.sys","C:\\WINDOWS\\System32\\DriverStore\\FileRepository\\zttap300.inf_amd64_f0b6dc883a479612\\zttap300.inf","ZeroTier Networks LLC","ZeroTier Networks LLC","zttap300","HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\zttap300","0","6.2.9200.20557"
```

**Comment by glimberg** [comment]
The Windows driver is most certainly signed.  Windows 10 won't load unsigned drivers.

**Comment by ecapuano** [comment]
Good point, let me look closer at this to determine why I am getting this response from osquery.

**Comment by glimberg** [comment]
If I had to guess, it's because it's not signed with an EV cert.  The driver was built before those requirements, and is still grandfathered in as valid under Microsoft's cryptic driver signing rules for Windows.  We haven't resigned it as we've made no changes to the driver in a long time and thus have had no reason to.

![image](https://user-images.githubusercontent.com/54439/45578684-e638e300-b837-11e8-983a-4ea43e3b0b9d.png)

**Comment by ecapuano** [comment]
Yep, checks out on the filesystem. 
![](https://puu.sh/Bv8Cv/26a4cab2ad.png)

Your theory is probably correct.

**Comment by adamierymenko** [comment]
You are welcome to attempt to build the NDIS6 driver. We are not responsible for any mental health issues such as post traumatic stress disorder that may follow.

**Comment by ecapuano** [comment]
Haha, I'll pass as I do not possess the required skillset. 

I'll whitelist it in my "bad stuff" detection logic in the meantime :)

**Comment by adamierymenko** [comment]
We have an EV cert and will sign it if/when we do rebuild it. I'm sure it will be required someday.

**Comment by hj-collab** [comment]
@adamierymenko @glimberg Will you please sign the driver? This one unsigned file makes it difficult for systems with AppLocker / WDAC to whitelist your app. All our systems are mandated to run only EV signed drivers for better security. Please consider this. We had to switch to tailscale because of this one point.

**Comment by glimberg** [comment]
@hj-collab this is a really old issues you're resurrecting. The driver is signed by an EV cert and has been for quite some time now

**Comment by hj-collab** [comment]
Ok. Just tried the latest version and it seems to be signed.
