### ISSUE TITLE
Windows Gui - Implement ListPeers (including name)

### ISSUE THREAD

**Issue by kevjustice** [zerotier/ZeroTierOne#957]
I'm used to Hamachi and being able to see peers and who is online.  Could you add this to the windows gui including the name of the peer?

**Comment by glimberg** [comment]
It used to be in the UI but caused more confusion than it helped. As such, we removed it.  The information is available from the command line, however.

Also, the concept of `peer` is not who's online on your network.  It's just other nodes that your ZeroTier node knows about. The peer list does not show the online/offline status of the node either.  Just the last time the nodes communicated with each other.  

Additionally, the "name" field of a node in a network is not known by the endpoints.  It's just metadata for the website. Since a node can be on multiple networks, it can have multiple names in Central. There is no single cannonical "name" for a node other than the 10 digit Node ID.
